// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: audit.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorType     string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorName     string                 `protobuf:"bytes,4,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorEmail    string                 `protobuf:"bytes,5,opt,name=actor_email,json=actorEmail,proto3" json:"actor_email,omitempty"`
	ServiceName   string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Action        string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,8,opt,name=resource,proto3" json:"resource,omitempty"`
	ResourceId    string                 `protobuf:"bytes,9,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	BeforeJson    string                 `protobuf:"bytes,10,opt,name=before_json,json=beforeJson,proto3" json:"before_json,omitempty"`
	AfterJson     string                 `protobuf:"bytes,11,opt,name=after_json,json=afterJson,proto3" json:"after_json,omitempty"`
	IpAddress     string                 `protobuf:"bytes,12,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,13,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Status        string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,15,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditLog) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *AuditLog) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *AuditLog) GetActorEmail() string {
	if x != nil {
		return x.ActorEmail
	}
	return ""
}

func (x *AuditLog) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditLog) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditLog) GetBeforeJson() string {
	if x != nil {
		return x.BeforeJson
	}
	return ""
}

func (x *AuditLog) GetAfterJson() string {
	if x != nil {
		return x.AfterJson
	}
	return ""
}

func (x *AuditLog) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuditLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AuditLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RecordAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorType     string                 `protobuf:"bytes,2,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorName     string                 `protobuf:"bytes,3,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorEmail    string                 `protobuf:"bytes,4,opt,name=actor_email,json=actorEmail,proto3" json:"actor_email,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,7,opt,name=resource,proto3" json:"resource,omitempty"`
	ResourceId    string                 `protobuf:"bytes,8,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	BeforeJson    string                 `protobuf:"bytes,9,opt,name=before_json,json=beforeJson,proto3" json:"before_json,omitempty"`
	AfterJson     string                 `protobuf:"bytes,10,opt,name=after_json,json=afterJson,proto3" json:"after_json,omitempty"`
	IpAddress     string                 `protobuf:"bytes,11,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,12,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,14,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAuditLogRequest) Reset() {
	*x = RecordAuditLogRequest{}
	mi := &file_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAuditLogRequest) ProtoMessage() {}

func (x *RecordAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAuditLogRequest.ProtoReflect.Descriptor instead.
func (*RecordAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{1}
}

func (x *RecordAuditLogRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RecordAuditLogRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *RecordAuditLogRequest) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *RecordAuditLogRequest) GetActorEmail() string {
	if x != nil {
		return x.ActorEmail
	}
	return ""
}

func (x *RecordAuditLogRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RecordAuditLogRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RecordAuditLogRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *RecordAuditLogRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *RecordAuditLogRequest) GetBeforeJson() string {
	if x != nil {
		return x.BeforeJson
	}
	return ""
}

func (x *RecordAuditLogRequest) GetAfterJson() string {
	if x != nil {
		return x.AfterJson
	}
	return ""
}

func (x *RecordAuditLogRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RecordAuditLogRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RecordAuditLogRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecordAuditLogRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RecordAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AuditLog      *AuditLog              `protobuf:"bytes,3,opt,name=audit_log,json=auditLog,proto3" json:"audit_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAuditLogResponse) Reset() {
	*x = RecordAuditLogResponse{}
	mi := &file_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAuditLogResponse) ProtoMessage() {}

func (x *RecordAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAuditLogResponse.ProtoReflect.Descriptor instead.
func (*RecordAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{2}
}

func (x *RecordAuditLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordAuditLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecordAuditLogResponse) GetAuditLog() *AuditLog {
	if x != nil {
		return x.AuditLog
	}
	return nil
}

type ListAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Search        string                 `protobuf:"bytes,6,opt,name=search,proto3" json:"search,omitempty"`
	StartDate     string                 `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page          int32                  `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsRequest) Reset() {
	*x = ListAuditLogsRequest{}
	mi := &file_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest) ProtoMessage() {}

func (x *ListAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{3}
}

func (x *ListAuditLogsRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ListAuditLogsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ListAuditLogsRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ListAuditLogsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListAuditLogsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAuditLogsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListAuditLogsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListAuditLogsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ListAuditLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditLogs     []*AuditLog            `protobuf:"bytes,1,rep,name=audit_logs,json=auditLogs,proto3" json:"audit_logs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsResponse) Reset() {
	*x = ListAuditLogsResponse{}
	mi := &file_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsResponse) ProtoMessage() {}

func (x *ListAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{4}
}

func (x *ListAuditLogsResponse) GetAuditLogs() []*AuditLog {
	if x != nil {
		return x.AuditLogs
	}
	return nil
}

func (x *ListAuditLogsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAuditLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuditLogsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogRequest) Reset() {
	*x = GetAuditLogRequest{}
	mi := &file_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogRequest) ProtoMessage() {}

func (x *GetAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuditLogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditLog      *AuditLog              `protobuf:"bytes,1,opt,name=audit_log,json=auditLog,proto3" json:"audit_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogResponse) Reset() {
	*x = GetAuditLogResponse{}
	mi := &file_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogResponse) ProtoMessage() {}

func (x *GetAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuditLogResponse) GetAuditLog() *AuditLog {
	if x != nil {
		return x.AuditLog
	}
	return nil
}

var File_audit_proto protoreflect.FileDescriptor

const file_audit_proto_rawDesc = "" +
	"\n" +
	"\vaudit.proto\x12\baudit.v1\"\xe6\x03\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x04 \x01(\tR\tactorName\x12\x1f\n" +
	"\vactor_email\x18\x05 \x01(\tR\n" +
	"actorEmail\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\b \x01(\tR\bresource\x12\x1f\n" +
	"\vresource_id\x18\t \x01(\tR\n" +
	"resourceId\x12\x1f\n" +
	"\vbefore_json\x18\n" +
	" \x01(\tR\n" +
	"beforeJson\x12\x1d\n" +
	"\n" +
	"after_json\x18\v \x01(\tR\tafterJson\x12\x1d\n" +
	"\n" +
	"ip_address\x18\f \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\r \x01(\tR\tuserAgent\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x0f \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\"\xc4\x03\n" +
	"\x15RecordAuditLogRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x02 \x01(\tR\tactorType\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x03 \x01(\tR\tactorName\x12\x1f\n" +
	"\vactor_email\x18\x04 \x01(\tR\n" +
	"actorEmail\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\a \x01(\tR\bresource\x12\x1f\n" +
	"\vresource_id\x18\b \x01(\tR\n" +
	"resourceId\x12\x1f\n" +
	"\vbefore_json\x18\t \x01(\tR\n" +
	"beforeJson\x12\x1d\n" +
	"\n" +
	"after_json\x18\n" +
	" \x01(\tR\tafterJson\x12\x1d\n" +
	"\n" +
	"ip_address\x18\v \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\f \x01(\tR\tuserAgent\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x0e \x01(\tR\ferrorMessage\"}\n" +
	"\x16RecordAuditLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\taudit_log\x18\x03 \x01(\v2\x12.audit.v1.AuditLogR\bauditLog\"\x9c\x02\n" +
	"\x14ListAuditLogsRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06search\x18\x06 \x01(\tR\x06search\x12\x1d\n" +
	"\n" +
	"start_date\x18\a \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\b \x01(\tR\aendDate\x12\x12\n" +
	"\x04page\x18\t \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x05R\x05limit\"\x8a\x01\n" +
	"\x15ListAuditLogsResponse\x121\n" +
	"\n" +
	"audit_logs\x18\x01 \x03(\v2\x12.audit.v1.AuditLogR\tauditLogs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"$\n" +
	"\x12GetAuditLogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x13GetAuditLogResponse\x12/\n" +
	"\taudit_log\x18\x01 \x01(\v2\x12.audit.v1.AuditLogR\bauditLog2\x81\x02\n" +
	"\fAuditService\x12S\n" +
	"\x0eRecordAuditLog\x12\x1f.audit.v1.RecordAuditLogRequest\x1a .audit.v1.RecordAuditLogResponse\x12P\n" +
	"\rListAuditLogs\x12\x1e.audit.v1.ListAuditLogsRequest\x1a\x1f.audit.v1.ListAuditLogsResponse\x12J\n" +
	"\vGetAuditLog\x12\x1c.audit.v1.GetAuditLogRequest\x1a\x1d.audit.v1.GetAuditLogResponseB#Z!auditService/api/proto/v1;auditv1b\x06proto3"

var (
	file_audit_proto_rawDescOnce sync.Once
	file_audit_proto_rawDescData []byte
)

func file_audit_proto_rawDescGZIP() []byte {
	file_audit_proto_rawDescOnce.Do(func() {
		file_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)))
	})
	return file_audit_proto_rawDescData
}

var file_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_audit_proto_goTypes = []any{
	(*AuditLog)(nil),               // 0: audit.v1.AuditLog
	(*RecordAuditLogRequest)(nil),  // 1: audit.v1.RecordAuditLogRequest
	(*RecordAuditLogResponse)(nil), // 2: audit.v1.RecordAuditLogResponse
	(*ListAuditLogsRequest)(nil),   // 3: audit.v1.ListAuditLogsRequest
	(*ListAuditLogsResponse)(nil),  // 4: audit.v1.ListAuditLogsResponse
	(*GetAuditLogRequest)(nil),     // 5: audit.v1.GetAuditLogRequest
	(*GetAuditLogResponse)(nil),    // 6: audit.v1.GetAuditLogResponse
}
var file_audit_proto_depIdxs = []int32{
	0, // 0: audit.v1.RecordAuditLogResponse.audit_log:type_name -> audit.v1.AuditLog
	0, // 1: audit.v1.ListAuditLogsResponse.audit_logs:type_name -> audit.v1.AuditLog
	0, // 2: audit.v1.GetAuditLogResponse.audit_log:type_name -> audit.v1.AuditLog
	1, // 3: audit.v1.AuditService.RecordAuditLog:input_type -> audit.v1.RecordAuditLogRequest
	3, // 4: audit.v1.AuditService.ListAuditLogs:input_type -> audit.v1.ListAuditLogsRequest
	5, // 5: audit.v1.AuditService.GetAuditLog:input_type -> audit.v1.GetAuditLogRequest
	2, // 6: audit.v1.AuditService.RecordAuditLog:output_type -> audit.v1.RecordAuditLogResponse
	4, // 7: audit.v1.AuditService.ListAuditLogs:output_type -> audit.v1.ListAuditLogsResponse
	6, // 8: audit.v1.AuditService.GetAuditLog:output_type -> audit.v1.GetAuditLogResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_audit_proto_init() }
func file_audit_proto_init() {
	if File_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_proto_goTypes,
		DependencyIndexes: file_audit_proto_depIdxs,
		MessageInfos:      file_audit_proto_msgTypes,
	}.Build()
	File_audit_proto = out.File
	file_audit_proto_goTypes = nil
	file_audit_proto_depIdxs = nil
}
