// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: webhook.proto

package webhookRunnerV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookCall struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId              string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName            string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	EventName          string                 `protobuf:"bytes,4,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	TargetUrl          string                 `protobuf:"bytes,5,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	PayloadJson        string                 `protobuf:"bytes,6,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	HeadersJson        string                 `protobuf:"bytes,7,opt,name=headers_json,json=headersJson,proto3" json:"headers_json,omitempty"`
	AttemptCount       int32                  `protobuf:"varint,8,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	Status             string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ResponseStatusCode int32                  `protobuf:"varint,10,opt,name=response_status_code,json=responseStatusCode,proto3" json:"response_status_code,omitempty"`
	ResponseBody       string                 `protobuf:"bytes,11,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ResponseLatencyMs  int64                  `protobuf:"varint,12,opt,name=response_latency_ms,json=responseLatencyMs,proto3" json:"response_latency_ms,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebhookCall) Reset() {
	*x = WebhookCall{}
	mi := &file_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookCall) ProtoMessage() {}

func (x *WebhookCall) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookCall.ProtoReflect.Descriptor instead.
func (*WebhookCall) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebhookCall) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WebhookCall) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *WebhookCall) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *WebhookCall) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *WebhookCall) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *WebhookCall) GetHeadersJson() string {
	if x != nil {
		return x.HeadersJson
	}
	return ""
}

func (x *WebhookCall) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *WebhookCall) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WebhookCall) GetResponseStatusCode() int32 {
	if x != nil {
		return x.ResponseStatusCode
	}
	return 0
}

func (x *WebhookCall) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *WebhookCall) GetResponseLatencyMs() int64 {
	if x != nil {
		return x.ResponseLatencyMs
	}
	return 0
}

func (x *WebhookCall) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WebhookCall) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WebhookCall) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SendWebhookRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AppId             string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	EventName         string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	PayloadJson       string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	CustomHeaders     map[string]string      `protobuf:"bytes,4,rep,name=custom_headers,json=customHeaders,proto3" json:"custom_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TargetUrlOverride string                 `protobuf:"bytes,5,opt,name=target_url_override,json=targetUrlOverride,proto3" json:"target_url_override,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendWebhookRequest) Reset() {
	*x = SendWebhookRequest{}
	mi := &file_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWebhookRequest) ProtoMessage() {}

func (x *SendWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWebhookRequest.ProtoReflect.Descriptor instead.
func (*SendWebhookRequest) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *SendWebhookRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SendWebhookRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *SendWebhookRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *SendWebhookRequest) GetCustomHeaders() map[string]string {
	if x != nil {
		return x.CustomHeaders
	}
	return nil
}

func (x *SendWebhookRequest) GetTargetUrlOverride() string {
	if x != nil {
		return x.TargetUrlOverride
	}
	return ""
}

type SendWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookCall   *WebhookCall           `protobuf:"bytes,1,opt,name=webhook_call,json=webhookCall,proto3" json:"webhook_call,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWebhookResponse) Reset() {
	*x = SendWebhookResponse{}
	mi := &file_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWebhookResponse) ProtoMessage() {}

func (x *SendWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWebhookResponse.ProtoReflect.Descriptor instead.
func (*SendWebhookResponse) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *SendWebhookResponse) GetWebhookCall() *WebhookCall {
	if x != nil {
		return x.WebhookCall
	}
	return nil
}

func (x *SendWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListWebhookCallsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Search        string                 `protobuf:"bytes,6,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhookCallsRequest) Reset() {
	*x = ListWebhookCallsRequest{}
	mi := &file_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookCallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookCallsRequest) ProtoMessage() {}

func (x *ListWebhookCallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhookCallsRequest.ProtoReflect.Descriptor instead.
func (*ListWebhookCallsRequest) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *ListWebhookCallsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListWebhookCallsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListWebhookCallsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListWebhookCallsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWebhookCallsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWebhookCallsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListWebhookCallsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookCalls  []*WebhookCall         `protobuf:"bytes,1,rep,name=webhook_calls,json=webhookCalls,proto3" json:"webhook_calls,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhookCallsResponse) Reset() {
	*x = ListWebhookCallsResponse{}
	mi := &file_webhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhookCallsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhookCallsResponse) ProtoMessage() {}

func (x *ListWebhookCallsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhookCallsResponse.ProtoReflect.Descriptor instead.
func (*ListWebhookCallsResponse) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{4}
}

func (x *ListWebhookCallsResponse) GetWebhookCalls() []*WebhookCall {
	if x != nil {
		return x.WebhookCalls
	}
	return nil
}

func (x *ListWebhookCallsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWebhookCallsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWebhookCallsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetWebhookCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookCallRequest) Reset() {
	*x = GetWebhookCallRequest{}
	mi := &file_webhook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookCallRequest) ProtoMessage() {}

func (x *GetWebhookCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookCallRequest.ProtoReflect.Descriptor instead.
func (*GetWebhookCallRequest) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{5}
}

func (x *GetWebhookCallRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetWebhookCallRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetWebhookCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookCall   *WebhookCall           `protobuf:"bytes,1,opt,name=webhook_call,json=webhookCall,proto3" json:"webhook_call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookCallResponse) Reset() {
	*x = GetWebhookCallResponse{}
	mi := &file_webhook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookCallResponse) ProtoMessage() {}

func (x *GetWebhookCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookCallResponse.ProtoReflect.Descriptor instead.
func (*GetWebhookCallResponse) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{6}
}

func (x *GetWebhookCallResponse) GetWebhookCall() *WebhookCall {
	if x != nil {
		return x.WebhookCall
	}
	return nil
}

type RetryWebhookCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryWebhookCallRequest) Reset() {
	*x = RetryWebhookCallRequest{}
	mi := &file_webhook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryWebhookCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryWebhookCallRequest) ProtoMessage() {}

func (x *RetryWebhookCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryWebhookCallRequest.ProtoReflect.Descriptor instead.
func (*RetryWebhookCallRequest) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{7}
}

func (x *RetryWebhookCallRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RetryWebhookCallRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RetryWebhookCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookCall   *WebhookCall           `protobuf:"bytes,1,opt,name=webhook_call,json=webhookCall,proto3" json:"webhook_call,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryWebhookCallResponse) Reset() {
	*x = RetryWebhookCallResponse{}
	mi := &file_webhook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryWebhookCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryWebhookCallResponse) ProtoMessage() {}

func (x *RetryWebhookCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryWebhookCallResponse.ProtoReflect.Descriptor instead.
func (*RetryWebhookCallResponse) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{8}
}

func (x *RetryWebhookCallResponse) GetWebhookCall() *WebhookCall {
	if x != nil {
		return x.WebhookCall
	}
	return nil
}

func (x *RetryWebhookCallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetryWebhookCallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_webhook_proto protoreflect.FileDescriptor

const file_webhook_proto_rawDesc = "" +
	"\n" +
	"\rwebhook.proto\x12\x11webhook_runner.v1\"\xfa\x03\n" +
	"\vWebhookCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x1d\n" +
	"\n" +
	"event_name\x18\x04 \x01(\tR\teventName\x12\x1d\n" +
	"\n" +
	"target_url\x18\x05 \x01(\tR\ttargetUrl\x12!\n" +
	"\fpayload_json\x18\x06 \x01(\tR\vpayloadJson\x12!\n" +
	"\fheaders_json\x18\a \x01(\tR\vheadersJson\x12#\n" +
	"\rattempt_count\x18\b \x01(\x05R\fattemptCount\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x120\n" +
	"\x14response_status_code\x18\n" +
	" \x01(\x05R\x12responseStatusCode\x12#\n" +
	"\rresponse_body\x18\v \x01(\tR\fresponseBody\x12.\n" +
	"\x13response_latency_ms\x18\f \x01(\x03R\x11responseLatencyMs\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\xc0\x02\n" +
	"\x12SendWebhookRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\x12_\n" +
	"\x0ecustom_headers\x18\x04 \x03(\v28.webhook_runner.v1.SendWebhookRequest.CustomHeadersEntryR\rcustomHeaders\x12.\n" +
	"\x13target_url_override\x18\x05 \x01(\tR\x11targetUrlOverride\x1a@\n" +
	"\x12CustomHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x13SendWebhookResponse\x12A\n" +
	"\fwebhook_call\x18\x01 \x01(\v2\x1e.webhook_runner.v1.WebhookCallR\vwebhookCall\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa3\x01\n" +
	"\x17ListWebhookCallsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06search\x18\x06 \x01(\tR\x06search\"\x9f\x01\n" +
	"\x18ListWebhookCallsResponse\x12C\n" +
	"\rwebhook_calls\x18\x01 \x03(\v2\x1e.webhook_runner.v1.WebhookCallR\fwebhookCalls\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"@\n" +
	"\x15GetWebhookCallRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"[\n" +
	"\x16GetWebhookCallResponse\x12A\n" +
	"\fwebhook_call\x18\x01 \x01(\v2\x1e.webhook_runner.v1.WebhookCallR\vwebhookCall\"B\n" +
	"\x17RetryWebhookCallRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x91\x01\n" +
	"\x18RetryWebhookCallResponse\x12A\n" +
	"\fwebhook_call\x18\x01 \x01(\v2\x1e.webhook_runner.v1.WebhookCallR\vwebhookCall\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xb5\x03\n" +
	"\x14WebhookRunnerService\x12\\\n" +
	"\vSendWebhook\x12%.webhook_runner.v1.SendWebhookRequest\x1a&.webhook_runner.v1.SendWebhookResponse\x12k\n" +
	"\x10ListWebhookCalls\x12*.webhook_runner.v1.ListWebhookCallsRequest\x1a+.webhook_runner.v1.ListWebhookCallsResponse\x12e\n" +
	"\x0eGetWebhookCall\x12(.webhook_runner.v1.GetWebhookCallRequest\x1a).webhook_runner.v1.GetWebhookCallResponse\x12k\n" +
	"\x10RetryWebhookCall\x12*.webhook_runner.v1.RetryWebhookCallRequest\x1a+.webhook_runner.v1.RetryWebhookCallResponseB,Z*webhookRunner/api/proto/v1;webhookRunnerV1b\x06proto3"

var (
	file_webhook_proto_rawDescOnce sync.Once
	file_webhook_proto_rawDescData []byte
)

func file_webhook_proto_rawDescGZIP() []byte {
	file_webhook_proto_rawDescOnce.Do(func() {
		file_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhook_proto_rawDesc), len(file_webhook_proto_rawDesc)))
	})
	return file_webhook_proto_rawDescData
}

var file_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_webhook_proto_goTypes = []any{
	(*WebhookCall)(nil),              // 0: webhook_runner.v1.WebhookCall
	(*SendWebhookRequest)(nil),       // 1: webhook_runner.v1.SendWebhookRequest
	(*SendWebhookResponse)(nil),      // 2: webhook_runner.v1.SendWebhookResponse
	(*ListWebhookCallsRequest)(nil),  // 3: webhook_runner.v1.ListWebhookCallsRequest
	(*ListWebhookCallsResponse)(nil), // 4: webhook_runner.v1.ListWebhookCallsResponse
	(*GetWebhookCallRequest)(nil),    // 5: webhook_runner.v1.GetWebhookCallRequest
	(*GetWebhookCallResponse)(nil),   // 6: webhook_runner.v1.GetWebhookCallResponse
	(*RetryWebhookCallRequest)(nil),  // 7: webhook_runner.v1.RetryWebhookCallRequest
	(*RetryWebhookCallResponse)(nil), // 8: webhook_runner.v1.RetryWebhookCallResponse
	nil,                              // 9: webhook_runner.v1.SendWebhookRequest.CustomHeadersEntry
}
var file_webhook_proto_depIdxs = []int32{
	9, // 0: webhook_runner.v1.SendWebhookRequest.custom_headers:type_name -> webhook_runner.v1.SendWebhookRequest.CustomHeadersEntry
	0, // 1: webhook_runner.v1.SendWebhookResponse.webhook_call:type_name -> webhook_runner.v1.WebhookCall
	0, // 2: webhook_runner.v1.ListWebhookCallsResponse.webhook_calls:type_name -> webhook_runner.v1.WebhookCall
	0, // 3: webhook_runner.v1.GetWebhookCallResponse.webhook_call:type_name -> webhook_runner.v1.WebhookCall
	0, // 4: webhook_runner.v1.RetryWebhookCallResponse.webhook_call:type_name -> webhook_runner.v1.WebhookCall
	1, // 5: webhook_runner.v1.WebhookRunnerService.SendWebhook:input_type -> webhook_runner.v1.SendWebhookRequest
	3, // 6: webhook_runner.v1.WebhookRunnerService.ListWebhookCalls:input_type -> webhook_runner.v1.ListWebhookCallsRequest
	5, // 7: webhook_runner.v1.WebhookRunnerService.GetWebhookCall:input_type -> webhook_runner.v1.GetWebhookCallRequest
	7, // 8: webhook_runner.v1.WebhookRunnerService.RetryWebhookCall:input_type -> webhook_runner.v1.RetryWebhookCallRequest
	2, // 9: webhook_runner.v1.WebhookRunnerService.SendWebhook:output_type -> webhook_runner.v1.SendWebhookResponse
	4, // 10: webhook_runner.v1.WebhookRunnerService.ListWebhookCalls:output_type -> webhook_runner.v1.ListWebhookCallsResponse
	6, // 11: webhook_runner.v1.WebhookRunnerService.GetWebhookCall:output_type -> webhook_runner.v1.GetWebhookCallResponse
	8, // 12: webhook_runner.v1.WebhookRunnerService.RetryWebhookCall:output_type -> webhook_runner.v1.RetryWebhookCallResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_webhook_proto_init() }
func file_webhook_proto_init() {
	if File_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhook_proto_rawDesc), len(file_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webhook_proto_goTypes,
		DependencyIndexes: file_webhook_proto_depIdxs,
		MessageInfos:      file_webhook_proto_msgTypes,
	}.Build()
	File_webhook_proto = out.File
	file_webhook_proto_goTypes = nil
	file_webhook_proto_depIdxs = nil
}
