// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/subscriptions/v1/plan.proto

package subscriptionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code              string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PriceMonthly      float64                `protobuf:"fixed64,5,opt,name=price_monthly,json=priceMonthly,proto3" json:"price_monthly,omitempty"`
	PriceAnnually     float64                `protobuf:"fixed64,6,opt,name=price_annually,json=priceAnnually,proto3" json:"price_annually,omitempty"`
	Currency          string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	MaxWebhooks       int32                  `protobuf:"varint,8,opt,name=max_webhooks,json=maxWebhooks,proto3" json:"max_webhooks,omitempty"`
	MaxEventsPerMonth int64                  `protobuf:"varint,9,opt,name=max_events_per_month,json=maxEventsPerMonth,proto3" json:"max_events_per_month,omitempty"`
	MaxTeamMembers    int32                  `protobuf:"varint,10,opt,name=max_team_members,json=maxTeamMembers,proto3" json:"max_team_members,omitempty"`
	Features          []string               `protobuf:"bytes,11,rep,name=features,proto3" json:"features,omitempty"`
	IsActive          bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsPopular         bool                   `protobuf:"varint,13,opt,name=is_popular,json=isPopular,proto3" json:"is_popular,omitempty"`
	TierLevel         int32                  `protobuf:"varint,14,opt,name=tier_level,json=tierLevel,proto3" json:"tier_level,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_plan_proto_rawDescGZIP(), []int{0}
}

func (x *PlanResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PlanResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlanResponse) GetPriceMonthly() float64 {
	if x != nil {
		return x.PriceMonthly
	}
	return 0
}

func (x *PlanResponse) GetPriceAnnually() float64 {
	if x != nil {
		return x.PriceAnnually
	}
	return 0
}

func (x *PlanResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PlanResponse) GetMaxWebhooks() int32 {
	if x != nil {
		return x.MaxWebhooks
	}
	return 0
}

func (x *PlanResponse) GetMaxEventsPerMonth() int64 {
	if x != nil {
		return x.MaxEventsPerMonth
	}
	return 0
}

func (x *PlanResponse) GetMaxTeamMembers() int32 {
	if x != nil {
		return x.MaxTeamMembers
	}
	return 0
}

func (x *PlanResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PlanResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PlanResponse) GetIsPopular() bool {
	if x != nil {
		return x.IsPopular
	}
	return false
}

func (x *PlanResponse) GetTierLevel() int32 {
	if x != nil {
		return x.TierLevel
	}
	return 0
}

func (x *PlanResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PlanResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreatePlanRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code              string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceMonthly      float64                `protobuf:"fixed64,4,opt,name=price_monthly,json=priceMonthly,proto3" json:"price_monthly,omitempty"`
	PriceAnnually     float64                `protobuf:"fixed64,5,opt,name=price_annually,json=priceAnnually,proto3" json:"price_annually,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	MaxWebhooks       int32                  `protobuf:"varint,7,opt,name=max_webhooks,json=maxWebhooks,proto3" json:"max_webhooks,omitempty"`
	MaxEventsPerMonth int64                  `protobuf:"varint,8,opt,name=max_events_per_month,json=maxEventsPerMonth,proto3" json:"max_events_per_month,omitempty"`
	MaxTeamMembers    int32                  `protobuf:"varint,9,opt,name=max_team_members,json=maxTeamMembers,proto3" json:"max_team_members,omitempty"`
	Features          []string               `protobuf:"bytes,10,rep,name=features,proto3" json:"features,omitempty"`
	IsActive          bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsPopular         bool                   `protobuf:"varint,12,opt,name=is_popular,json=isPopular,proto3" json:"is_popular,omitempty"`
	TierLevel         int32                  `protobuf:"varint,13,opt,name=tier_level,json=tierLevel,proto3" json:"tier_level,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePlanRequest) Reset() {
	*x = CreatePlanRequest{}
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanRequest) ProtoMessage() {}

func (x *CreatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanRequest.ProtoReflect.Descriptor instead.
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_plan_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlanRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePlanRequest) GetPriceMonthly() float64 {
	if x != nil {
		return x.PriceMonthly
	}
	return 0
}

func (x *CreatePlanRequest) GetPriceAnnually() float64 {
	if x != nil {
		return x.PriceAnnually
	}
	return 0
}

func (x *CreatePlanRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePlanRequest) GetMaxWebhooks() int32 {
	if x != nil {
		return x.MaxWebhooks
	}
	return 0
}

func (x *CreatePlanRequest) GetMaxEventsPerMonth() int64 {
	if x != nil {
		return x.MaxEventsPerMonth
	}
	return 0
}

func (x *CreatePlanRequest) GetMaxTeamMembers() int32 {
	if x != nil {
		return x.MaxTeamMembers
	}
	return 0
}

func (x *CreatePlanRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *CreatePlanRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreatePlanRequest) GetIsPopular() bool {
	if x != nil {
		return x.IsPopular
	}
	return false
}

func (x *CreatePlanRequest) GetTierLevel() int32 {
	if x != nil {
		return x.TierLevel
	}
	return 0
}

type UpdatePlanRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceMonthly      float64                `protobuf:"fixed64,4,opt,name=price_monthly,json=priceMonthly,proto3" json:"price_monthly,omitempty"`
	PriceAnnually     float64                `protobuf:"fixed64,5,opt,name=price_annually,json=priceAnnually,proto3" json:"price_annually,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	MaxWebhooks       int32                  `protobuf:"varint,7,opt,name=max_webhooks,json=maxWebhooks,proto3" json:"max_webhooks,omitempty"`
	MaxEventsPerMonth int64                  `protobuf:"varint,8,opt,name=max_events_per_month,json=maxEventsPerMonth,proto3" json:"max_events_per_month,omitempty"`
	MaxTeamMembers    int32                  `protobuf:"varint,9,opt,name=max_team_members,json=maxTeamMembers,proto3" json:"max_team_members,omitempty"`
	Features          []string               `protobuf:"bytes,10,rep,name=features,proto3" json:"features,omitempty"`
	IsActive          bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsPopular         bool                   `protobuf:"varint,12,opt,name=is_popular,json=isPopular,proto3" json:"is_popular,omitempty"`
	TierLevel         int32                  `protobuf:"varint,13,opt,name=tier_level,json=tierLevel,proto3" json:"tier_level,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdatePlanRequest) Reset() {
	*x = UpdatePlanRequest{}
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanRequest) ProtoMessage() {}

func (x *UpdatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_plan_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePlanRequest) GetPriceMonthly() float64 {
	if x != nil {
		return x.PriceMonthly
	}
	return 0
}

func (x *UpdatePlanRequest) GetPriceAnnually() float64 {
	if x != nil {
		return x.PriceAnnually
	}
	return 0
}

func (x *UpdatePlanRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdatePlanRequest) GetMaxWebhooks() int32 {
	if x != nil {
		return x.MaxWebhooks
	}
	return 0
}

func (x *UpdatePlanRequest) GetMaxEventsPerMonth() int64 {
	if x != nil {
		return x.MaxEventsPerMonth
	}
	return 0
}

func (x *UpdatePlanRequest) GetMaxTeamMembers() int32 {
	if x != nil {
		return x.MaxTeamMembers
	}
	return 0
}

func (x *UpdatePlanRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *UpdatePlanRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdatePlanRequest) GetIsPopular() bool {
	if x != nil {
		return x.IsPopular
	}
	return false
}

func (x *UpdatePlanRequest) GetTierLevel() int32 {
	if x != nil {
		return x.TierLevel
	}
	return 0
}

type GetPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_plan_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanRequest) Reset() {
	*x = DeletePlanRequest{}
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanRequest) ProtoMessage() {}

func (x *DeletePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanRequest.ProtoReflect.Descriptor instead.
func (*DeletePlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_plan_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanResponse) Reset() {
	*x = DeletePlanResponse{}
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanResponse) ProtoMessage() {}

func (x *DeletePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanResponse.ProtoReflect.Descriptor instead.
func (*DeletePlanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_plan_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePlanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPlansRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeInactive bool                   `protobuf:"varint,1,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_plan_proto_rawDescGZIP(), []int{6}
}

func (x *ListPlansRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type ListPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*PlanResponse        `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_plan_proto_rawDescGZIP(), []int{7}
}

func (x *ListPlansResponse) GetPlans() []*PlanResponse {
	if x != nil {
		return x.Plans
	}
	return nil
}

var File_api_proto_subscriptions_v1_plan_proto protoreflect.FileDescriptor

const file_api_proto_subscriptions_v1_plan_proto_rawDesc = "" +
	"\n" +
	"%api/proto/subscriptions/v1/plan.proto\x12\x10subscriptions.v1\"\x83\x04\n" +
	"\fPlanResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rprice_monthly\x18\x05 \x01(\x01R\fpriceMonthly\x12%\n" +
	"\x0eprice_annually\x18\x06 \x01(\x01R\rpriceAnnually\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12!\n" +
	"\fmax_webhooks\x18\b \x01(\x05R\vmaxWebhooks\x12/\n" +
	"\x14max_events_per_month\x18\t \x01(\x03R\x11maxEventsPerMonth\x12(\n" +
	"\x10max_team_members\x18\n" +
	" \x01(\x05R\x0emaxTeamMembers\x12\x1a\n" +
	"\bfeatures\x18\v \x03(\tR\bfeatures\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_popular\x18\r \x01(\bR\tisPopular\x12\x1d\n" +
	"\n" +
	"tier_level\x18\x0e \x01(\x05R\ttierLevel\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\"\xba\x03\n" +
	"\x11CreatePlanRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rprice_monthly\x18\x04 \x01(\x01R\fpriceMonthly\x12%\n" +
	"\x0eprice_annually\x18\x05 \x01(\x01R\rpriceAnnually\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\fmax_webhooks\x18\a \x01(\x05R\vmaxWebhooks\x12/\n" +
	"\x14max_events_per_month\x18\b \x01(\x03R\x11maxEventsPerMonth\x12(\n" +
	"\x10max_team_members\x18\t \x01(\x05R\x0emaxTeamMembers\x12\x1a\n" +
	"\bfeatures\x18\n" +
	" \x03(\tR\bfeatures\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_popular\x18\f \x01(\bR\tisPopular\x12\x1d\n" +
	"\n" +
	"tier_level\x18\r \x01(\x05R\ttierLevel\"\xb6\x03\n" +
	"\x11UpdatePlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rprice_monthly\x18\x04 \x01(\x01R\fpriceMonthly\x12%\n" +
	"\x0eprice_annually\x18\x05 \x01(\x01R\rpriceAnnually\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\fmax_webhooks\x18\a \x01(\x05R\vmaxWebhooks\x12/\n" +
	"\x14max_events_per_month\x18\b \x01(\x03R\x11maxEventsPerMonth\x12(\n" +
	"\x10max_team_members\x18\t \x01(\x05R\x0emaxTeamMembers\x12\x1a\n" +
	"\bfeatures\x18\n" +
	" \x03(\tR\bfeatures\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"is_popular\x18\f \x01(\bR\tisPopular\x12\x1d\n" +
	"\n" +
	"tier_level\x18\r \x01(\x05R\ttierLevel\" \n" +
	"\x0eGetPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11DeletePlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x12DeletePlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x10ListPlansRequest\x12)\n" +
	"\x10include_inactive\x18\x01 \x01(\bR\x0fincludeInactive\"I\n" +
	"\x11ListPlansResponse\x124\n" +
	"\x05plans\x18\x01 \x03(\v2\x1e.subscriptions.v1.PlanResponseR\x05plans2\xaf\x03\n" +
	"\vPlanService\x12Q\n" +
	"\n" +
	"CreatePlan\x12#.subscriptions.v1.CreatePlanRequest\x1a\x1e.subscriptions.v1.PlanResponse\x12K\n" +
	"\aGetPlan\x12 .subscriptions.v1.GetPlanRequest\x1a\x1e.subscriptions.v1.PlanResponse\x12Q\n" +
	"\n" +
	"UpdatePlan\x12#.subscriptions.v1.UpdatePlanRequest\x1a\x1e.subscriptions.v1.PlanResponse\x12W\n" +
	"\n" +
	"DeletePlan\x12#.subscriptions.v1.DeletePlanRequest\x1a$.subscriptions.v1.DeletePlanResponse\x12T\n" +
	"\tListPlans\x12\".subscriptions.v1.ListPlansRequest\x1a#.subscriptions.v1.ListPlansResponseB>Z<webhookApiGateway/api/proto/subscriptions/v1;subscriptionsv1b\x06proto3"

var (
	file_api_proto_subscriptions_v1_plan_proto_rawDescOnce sync.Once
	file_api_proto_subscriptions_v1_plan_proto_rawDescData []byte
)

func file_api_proto_subscriptions_v1_plan_proto_rawDescGZIP() []byte {
	file_api_proto_subscriptions_v1_plan_proto_rawDescOnce.Do(func() {
		file_api_proto_subscriptions_v1_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_subscriptions_v1_plan_proto_rawDesc), len(file_api_proto_subscriptions_v1_plan_proto_rawDesc)))
	})
	return file_api_proto_subscriptions_v1_plan_proto_rawDescData
}

var file_api_proto_subscriptions_v1_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_subscriptions_v1_plan_proto_goTypes = []any{
	(*PlanResponse)(nil),       // 0: subscriptions.v1.PlanResponse
	(*CreatePlanRequest)(nil),  // 1: subscriptions.v1.CreatePlanRequest
	(*UpdatePlanRequest)(nil),  // 2: subscriptions.v1.UpdatePlanRequest
	(*GetPlanRequest)(nil),     // 3: subscriptions.v1.GetPlanRequest
	(*DeletePlanRequest)(nil),  // 4: subscriptions.v1.DeletePlanRequest
	(*DeletePlanResponse)(nil), // 5: subscriptions.v1.DeletePlanResponse
	(*ListPlansRequest)(nil),   // 6: subscriptions.v1.ListPlansRequest
	(*ListPlansResponse)(nil),  // 7: subscriptions.v1.ListPlansResponse
}
var file_api_proto_subscriptions_v1_plan_proto_depIdxs = []int32{
	0, // 0: subscriptions.v1.ListPlansResponse.plans:type_name -> subscriptions.v1.PlanResponse
	1, // 1: subscriptions.v1.PlanService.CreatePlan:input_type -> subscriptions.v1.CreatePlanRequest
	3, // 2: subscriptions.v1.PlanService.GetPlan:input_type -> subscriptions.v1.GetPlanRequest
	2, // 3: subscriptions.v1.PlanService.UpdatePlan:input_type -> subscriptions.v1.UpdatePlanRequest
	4, // 4: subscriptions.v1.PlanService.DeletePlan:input_type -> subscriptions.v1.DeletePlanRequest
	6, // 5: subscriptions.v1.PlanService.ListPlans:input_type -> subscriptions.v1.ListPlansRequest
	0, // 6: subscriptions.v1.PlanService.CreatePlan:output_type -> subscriptions.v1.PlanResponse
	0, // 7: subscriptions.v1.PlanService.GetPlan:output_type -> subscriptions.v1.PlanResponse
	0, // 8: subscriptions.v1.PlanService.UpdatePlan:output_type -> subscriptions.v1.PlanResponse
	5, // 9: subscriptions.v1.PlanService.DeletePlan:output_type -> subscriptions.v1.DeletePlanResponse
	7, // 10: subscriptions.v1.PlanService.ListPlans:output_type -> subscriptions.v1.ListPlansResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_subscriptions_v1_plan_proto_init() }
func file_api_proto_subscriptions_v1_plan_proto_init() {
	if File_api_proto_subscriptions_v1_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_subscriptions_v1_plan_proto_rawDesc), len(file_api_proto_subscriptions_v1_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_subscriptions_v1_plan_proto_goTypes,
		DependencyIndexes: file_api_proto_subscriptions_v1_plan_proto_depIdxs,
		MessageInfos:      file_api_proto_subscriptions_v1_plan_proto_msgTypes,
	}.Build()
	File_api_proto_subscriptions_v1_plan_proto = out.File
	file_api_proto_subscriptions_v1_plan_proto_goTypes = nil
	file_api_proto_subscriptions_v1_plan_proto_depIdxs = nil
}
