// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/subscriptions/v1/subscription.proto

package subscriptionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId             string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Plan               *PlanResponse          `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                 // active, pending_manual_payment, trialing, past_due, canceled, expired
	BillingCycle       string                 `protobuf:"bytes,6,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"` // monthly, annually
	CurrentPeriodStart string                 `protobuf:"bytes,7,opt,name=current_period_start,json=currentPeriodStart,proto3" json:"current_period_start,omitempty"`
	CurrentPeriodEnd   string                 `protobuf:"bytes,8,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	TrialEndsAt        string                 `protobuf:"bytes,9,opt,name=trial_ends_at,json=trialEndsAt,proto3" json:"trial_ends_at,omitempty"`
	CancelAtPeriodEnd  bool                   `protobuf:"varint,10,opt,name=cancel_at_period_end,json=cancelAtPeriodEnd,proto3" json:"cancel_at_period_end,omitempty"`
	CustomNotes        string                 `protobuf:"bytes,11,opt,name=custom_notes,json=customNotes,proto3" json:"custom_notes,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscriptionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscriptionResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubscriptionResponse) GetPlan() *PlanResponse {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *SubscriptionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubscriptionResponse) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *SubscriptionResponse) GetCurrentPeriodStart() string {
	if x != nil {
		return x.CurrentPeriodStart
	}
	return ""
}

func (x *SubscriptionResponse) GetCurrentPeriodEnd() string {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return ""
}

func (x *SubscriptionResponse) GetTrialEndsAt() string {
	if x != nil {
		return x.TrialEndsAt
	}
	return ""
}

func (x *SubscriptionResponse) GetCancelAtPeriodEnd() bool {
	if x != nil {
		return x.CancelAtPeriodEnd
	}
	return false
}

func (x *SubscriptionResponse) GetCustomNotes() string {
	if x != nil {
		return x.CustomNotes
	}
	return ""
}

func (x *SubscriptionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SubscriptionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	BillingCycle  string                 `protobuf:"bytes,3,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`    // monthly, annually
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // bank_transfer, wire, cash, check
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscribeRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubscribeRequest) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *SubscribeRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *SubscribeRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type SubscribeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Subscription        *SubscriptionResponse  `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	InvoiceId           string                 `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	InvoiceNumber       string                 `protobuf:"bytes,3,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	AmountDue           float64                `protobuf:"fixed64,4,opt,name=amount_due,json=amountDue,proto3" json:"amount_due,omitempty"`
	Currency            string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentInstructions string                 `protobuf:"bytes,6,opt,name=payment_instructions,json=paymentInstructions,proto3" json:"payment_instructions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeResponse) GetSubscription() *SubscriptionResponse {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *SubscribeResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *SubscribeResponse) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *SubscribeResponse) GetAmountDue() float64 {
	if x != nil {
		return x.AmountDue
	}
	return 0
}

func (x *SubscribeResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SubscribeResponse) GetPaymentInstructions() string {
	if x != nil {
		return x.PaymentInstructions
	}
	return ""
}

type GetUserSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionRequest) Reset() {
	*x = GetUserSubscriptionRequest{}
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionRequest) ProtoMessage() {}

func (x *GetUserSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Immediately   bool                   `protobuf:"varint,3,opt,name=immediately,proto3" json:"immediately,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *CancelSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelSubscriptionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelSubscriptionRequest) GetImmediately() bool {
	if x != nil {
		return x.Immediately
	}
	return false
}

type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Subscription  *SubscriptionResponse  `protobuf:"bytes,3,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *CancelSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelSubscriptionResponse) GetSubscription() *SubscriptionResponse {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type AdminOverrideSubscriptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId           string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPeriodEnd string                 `protobuf:"bytes,4,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	AdminNotes       string                 `protobuf:"bytes,5,opt,name=admin_notes,json=adminNotes,proto3" json:"admin_notes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminOverrideSubscriptionRequest) Reset() {
	*x = AdminOverrideSubscriptionRequest{}
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminOverrideSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOverrideSubscriptionRequest) ProtoMessage() {}

func (x *AdminOverrideSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOverrideSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*AdminOverrideSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *AdminOverrideSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminOverrideSubscriptionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *AdminOverrideSubscriptionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminOverrideSubscriptionRequest) GetCurrentPeriodEnd() string {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return ""
}

func (x *AdminOverrideSubscriptionRequest) GetAdminNotes() string {
	if x != nil {
		return x.AdminNotes
	}
	return ""
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubscriptionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSubscriptionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSubscriptionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListSubscriptionsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Subscriptions []*SubscriptionResponse `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	TotalItems    int64                   `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	CurrentPage   int32                   `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                   `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscriptions_v1_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*SubscriptionResponse {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *ListSubscriptionsResponse) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ListSubscriptionsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ListSubscriptionsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_api_proto_subscriptions_v1_subscription_proto protoreflect.FileDescriptor

const file_api_proto_subscriptions_v1_subscription_proto_rawDesc = "" +
	"\n" +
	"-api/proto/subscriptions/v1/subscription.proto\x12\x10subscriptions.v1\x1a%api/proto/subscriptions/v1/plan.proto\"\xdf\x03\n" +
	"\x14SubscriptionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x122\n" +
	"\x04plan\x18\x04 \x01(\v2\x1e.subscriptions.v1.PlanResponseR\x04plan\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rbilling_cycle\x18\x06 \x01(\tR\fbillingCycle\x120\n" +
	"\x14current_period_start\x18\a \x01(\tR\x12currentPeriodStart\x12,\n" +
	"\x12current_period_end\x18\b \x01(\tR\x10currentPeriodEnd\x12\"\n" +
	"\rtrial_ends_at\x18\t \x01(\tR\vtrialEndsAt\x12/\n" +
	"\x14cancel_at_period_end\x18\n" +
	" \x01(\bR\x11cancelAtPeriodEnd\x12!\n" +
	"\fcustom_notes\x18\v \x01(\tR\vcustomNotes\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"\xa6\x01\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12#\n" +
	"\rbilling_cycle\x18\x03 \x01(\tR\fbillingCycle\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\x93\x02\n" +
	"\x11SubscribeResponse\x12J\n" +
	"\fsubscription\x18\x01 \x01(\v2&.subscriptions.v1.SubscriptionResponseR\fsubscription\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x02 \x01(\tR\tinvoiceId\x12%\n" +
	"\x0einvoice_number\x18\x03 \x01(\tR\rinvoiceNumber\x12\x1d\n" +
	"\n" +
	"amount_due\x18\x04 \x01(\x01R\tamountDue\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x121\n" +
	"\x14payment_instructions\x18\x06 \x01(\tR\x13paymentInstructions\"5\n" +
	"\x1aGetUserSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"n\n" +
	"\x19CancelSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12 \n" +
	"\vimmediately\x18\x03 \x01(\bR\vimmediately\"\x9c\x01\n" +
	"\x1aCancelSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12J\n" +
	"\fsubscription\x18\x03 \x01(\v2&.subscriptions.v1.SubscriptionResponseR\fsubscription\"\xbb\x01\n" +
	" AdminOverrideSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12,\n" +
	"\x12current_period_end\x18\x04 \x01(\tR\x10currentPeriodEnd\x12\x1f\n" +
	"\vadmin_notes\x18\x05 \x01(\tR\n" +
	"adminNotes\"{\n" +
	"\x18ListSubscriptionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\xce\x01\n" +
	"\x19ListSubscriptionsResponse\x12L\n" +
	"\rsubscriptions\x18\x01 \x03(\v2&.subscriptions.v1.SubscriptionResponseR\rsubscriptions\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x03R\n" +
	"totalItems\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages2\xb0\x04\n" +
	"\x13SubscriptionService\x12T\n" +
	"\tSubscribe\x12\".subscriptions.v1.SubscribeRequest\x1a#.subscriptions.v1.SubscribeResponse\x12k\n" +
	"\x13GetUserSubscription\x12,.subscriptions.v1.GetUserSubscriptionRequest\x1a&.subscriptions.v1.SubscriptionResponse\x12o\n" +
	"\x12CancelSubscription\x12+.subscriptions.v1.CancelSubscriptionRequest\x1a,.subscriptions.v1.CancelSubscriptionResponse\x12w\n" +
	"\x19AdminOverrideSubscription\x122.subscriptions.v1.AdminOverrideSubscriptionRequest\x1a&.subscriptions.v1.SubscriptionResponse\x12l\n" +
	"\x11ListSubscriptions\x12*.subscriptions.v1.ListSubscriptionsRequest\x1a+.subscriptions.v1.ListSubscriptionsResponseB>Z<webhookApiGateway/api/proto/subscriptions/v1;subscriptionsv1b\x06proto3"

var (
	file_api_proto_subscriptions_v1_subscription_proto_rawDescOnce sync.Once
	file_api_proto_subscriptions_v1_subscription_proto_rawDescData []byte
)

func file_api_proto_subscriptions_v1_subscription_proto_rawDescGZIP() []byte {
	file_api_proto_subscriptions_v1_subscription_proto_rawDescOnce.Do(func() {
		file_api_proto_subscriptions_v1_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_subscriptions_v1_subscription_proto_rawDesc), len(file_api_proto_subscriptions_v1_subscription_proto_rawDesc)))
	})
	return file_api_proto_subscriptions_v1_subscription_proto_rawDescData
}

var file_api_proto_subscriptions_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_subscriptions_v1_subscription_proto_goTypes = []any{
	(*SubscriptionResponse)(nil),             // 0: subscriptions.v1.SubscriptionResponse
	(*SubscribeRequest)(nil),                 // 1: subscriptions.v1.SubscribeRequest
	(*SubscribeResponse)(nil),                // 2: subscriptions.v1.SubscribeResponse
	(*GetUserSubscriptionRequest)(nil),       // 3: subscriptions.v1.GetUserSubscriptionRequest
	(*CancelSubscriptionRequest)(nil),        // 4: subscriptions.v1.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil),       // 5: subscriptions.v1.CancelSubscriptionResponse
	(*AdminOverrideSubscriptionRequest)(nil), // 6: subscriptions.v1.AdminOverrideSubscriptionRequest
	(*ListSubscriptionsRequest)(nil),         // 7: subscriptions.v1.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),        // 8: subscriptions.v1.ListSubscriptionsResponse
	(*PlanResponse)(nil),                     // 9: subscriptions.v1.PlanResponse
}
var file_api_proto_subscriptions_v1_subscription_proto_depIdxs = []int32{
	9, // 0: subscriptions.v1.SubscriptionResponse.plan:type_name -> subscriptions.v1.PlanResponse
	0, // 1: subscriptions.v1.SubscribeResponse.subscription:type_name -> subscriptions.v1.SubscriptionResponse
	0, // 2: subscriptions.v1.CancelSubscriptionResponse.subscription:type_name -> subscriptions.v1.SubscriptionResponse
	0, // 3: subscriptions.v1.ListSubscriptionsResponse.subscriptions:type_name -> subscriptions.v1.SubscriptionResponse
	1, // 4: subscriptions.v1.SubscriptionService.Subscribe:input_type -> subscriptions.v1.SubscribeRequest
	3, // 5: subscriptions.v1.SubscriptionService.GetUserSubscription:input_type -> subscriptions.v1.GetUserSubscriptionRequest
	4, // 6: subscriptions.v1.SubscriptionService.CancelSubscription:input_type -> subscriptions.v1.CancelSubscriptionRequest
	6, // 7: subscriptions.v1.SubscriptionService.AdminOverrideSubscription:input_type -> subscriptions.v1.AdminOverrideSubscriptionRequest
	7, // 8: subscriptions.v1.SubscriptionService.ListSubscriptions:input_type -> subscriptions.v1.ListSubscriptionsRequest
	2, // 9: subscriptions.v1.SubscriptionService.Subscribe:output_type -> subscriptions.v1.SubscribeResponse
	0, // 10: subscriptions.v1.SubscriptionService.GetUserSubscription:output_type -> subscriptions.v1.SubscriptionResponse
	5, // 11: subscriptions.v1.SubscriptionService.CancelSubscription:output_type -> subscriptions.v1.CancelSubscriptionResponse
	0, // 12: subscriptions.v1.SubscriptionService.AdminOverrideSubscription:output_type -> subscriptions.v1.SubscriptionResponse
	8, // 13: subscriptions.v1.SubscriptionService.ListSubscriptions:output_type -> subscriptions.v1.ListSubscriptionsResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_subscriptions_v1_subscription_proto_init() }
func file_api_proto_subscriptions_v1_subscription_proto_init() {
	if File_api_proto_subscriptions_v1_subscription_proto != nil {
		return
	}
	file_api_proto_subscriptions_v1_plan_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_subscriptions_v1_subscription_proto_rawDesc), len(file_api_proto_subscriptions_v1_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_subscriptions_v1_subscription_proto_goTypes,
		DependencyIndexes: file_api_proto_subscriptions_v1_subscription_proto_depIdxs,
		MessageInfos:      file_api_proto_subscriptions_v1_subscription_proto_msgTypes,
	}.Build()
	File_api_proto_subscriptions_v1_subscription_proto = out.File
	file_api_proto_subscriptions_v1_subscription_proto_goTypes = nil
	file_api_proto_subscriptions_v1_subscription_proto_depIdxs = nil
}
