// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/v1/invoice.proto

package subscriptionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvoiceItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Total         float64                `protobuf:"fixed64,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceItemResponse) Reset() {
	*x = InvoiceItemResponse{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceItemResponse) ProtoMessage() {}

func (x *InvoiceItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceItemResponse.ProtoReflect.Descriptor instead.
func (*InvoiceItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *InvoiceItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvoiceItemResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InvoiceItemResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InvoiceItemResponse) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *InvoiceItemResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type InvoiceResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceNumber           string                 `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	SubscriptionId          string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	UserId                  string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount                  float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Tax                     float64                `protobuf:"fixed64,6,opt,name=tax,proto3" json:"tax,omitempty"`
	TotalAmount             float64                `protobuf:"fixed64,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Currency                string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Status                  string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"` // draft, unpaid, paid, void, overdue
	DueDate                 string                 `protobuf:"bytes,10,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	PaidAt                  string                 `protobuf:"bytes,11,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	PaymentMethod           string                 `protobuf:"bytes,12,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentReference        string                 `protobuf:"bytes,13,opt,name=payment_reference,json=paymentReference,proto3" json:"payment_reference,omitempty"`
	BankAccountInstructions string                 `protobuf:"bytes,14,opt,name=bank_account_instructions,json=bankAccountInstructions,proto3" json:"bank_account_instructions,omitempty"`
	Notes                   string                 `protobuf:"bytes,15,opt,name=notes,proto3" json:"notes,omitempty"`
	Items                   []*InvoiceItemResponse `protobuf:"bytes,16,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt               string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               string                 `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InvoiceResponse) Reset() {
	*x = InvoiceResponse{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceResponse) ProtoMessage() {}

func (x *InvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceResponse.ProtoReflect.Descriptor instead.
func (*InvoiceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{1}
}

func (x *InvoiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvoiceResponse) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *InvoiceResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *InvoiceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InvoiceResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InvoiceResponse) GetTax() float64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *InvoiceResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *InvoiceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InvoiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InvoiceResponse) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *InvoiceResponse) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *InvoiceResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *InvoiceResponse) GetPaymentReference() string {
	if x != nil {
		return x.PaymentReference
	}
	return ""
}

func (x *InvoiceResponse) GetBankAccountInstructions() string {
	if x != nil {
		return x.BankAccountInstructions
	}
	return ""
}

func (x *InvoiceResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *InvoiceResponse) GetItems() []*InvoiceItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InvoiceResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *InvoiceResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateInvoiceItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceItemInput) Reset() {
	*x = CreateInvoiceItemInput{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceItemInput) ProtoMessage() {}

func (x *CreateInvoiceItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceItemInput.ProtoReflect.Descriptor instead.
func (*CreateInvoiceItemInput) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInvoiceItemInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateInvoiceItemInput) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateInvoiceItemInput) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

type CreateManualInvoiceRequest struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	UserId                  string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionId          string                    `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Amount                  float64                   `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Tax                     float64                   `protobuf:"fixed64,4,opt,name=tax,proto3" json:"tax,omitempty"`
	Currency                string                    `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	DueDate                 string                    `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Notes                   string                    `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	BankAccountInstructions string                    `protobuf:"bytes,8,opt,name=bank_account_instructions,json=bankAccountInstructions,proto3" json:"bank_account_instructions,omitempty"`
	Items                   []*CreateInvoiceItemInput `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CreateManualInvoiceRequest) Reset() {
	*x = CreateManualInvoiceRequest{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManualInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManualInvoiceRequest) ProtoMessage() {}

func (x *CreateManualInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManualInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateManualInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{3}
}

func (x *CreateManualInvoiceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateManualInvoiceRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CreateManualInvoiceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateManualInvoiceRequest) GetTax() float64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *CreateManualInvoiceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateManualInvoiceRequest) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *CreateManualInvoiceRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreateManualInvoiceRequest) GetBankAccountInstructions() string {
	if x != nil {
		return x.BankAccountInstructions
	}
	return ""
}

func (x *CreateManualInvoiceRequest) GetItems() []*CreateInvoiceItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{4}
}

func (x *GetInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // optional filter by user
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`               // optional filter by status
	Search        string                 `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesRequest) Reset() {
	*x = ListInvoicesRequest{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesRequest) ProtoMessage() {}

func (x *ListInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesRequest.ProtoReflect.Descriptor instead.
func (*ListInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{5}
}

func (x *ListInvoicesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListInvoicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInvoicesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListInvoicesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListInvoicesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*InvoiceResponse     `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	TotalItems    int64                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesResponse) Reset() {
	*x = ListInvoicesResponse{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesResponse) ProtoMessage() {}

func (x *ListInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesResponse.ProtoReflect.Descriptor instead.
func (*ListInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{6}
}

func (x *ListInvoicesResponse) GetInvoices() []*InvoiceResponse {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *ListInvoicesResponse) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ListInvoicesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ListInvoicesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type MarkInvoicePaidRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId        string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	PaymentReference string                 `protobuf:"bytes,2,opt,name=payment_reference,json=paymentReference,proto3" json:"payment_reference,omitempty"`
	PaymentMethod    string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	AdminNotes       string                 `protobuf:"bytes,4,opt,name=admin_notes,json=adminNotes,proto3" json:"admin_notes,omitempty"`
	AdminId          string                 `protobuf:"bytes,5,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarkInvoicePaidRequest) Reset() {
	*x = MarkInvoicePaidRequest{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkInvoicePaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkInvoicePaidRequest) ProtoMessage() {}

func (x *MarkInvoicePaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkInvoicePaidRequest.ProtoReflect.Descriptor instead.
func (*MarkInvoicePaidRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{7}
}

func (x *MarkInvoicePaidRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *MarkInvoicePaidRequest) GetPaymentReference() string {
	if x != nil {
		return x.PaymentReference
	}
	return ""
}

func (x *MarkInvoicePaidRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *MarkInvoicePaidRequest) GetAdminNotes() string {
	if x != nil {
		return x.AdminNotes
	}
	return ""
}

func (x *MarkInvoicePaidRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type VoidInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidInvoiceRequest) Reset() {
	*x = VoidInvoiceRequest{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidInvoiceRequest) ProtoMessage() {}

func (x *VoidInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidInvoiceRequest.ProtoReflect.Descriptor instead.
func (*VoidInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{8}
}

func (x *VoidInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *VoidInvoiceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type VoidInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Invoice       *InvoiceResponse       `protobuf:"bytes,3,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidInvoiceResponse) Reset() {
	*x = VoidInvoiceResponse{}
	mi := &file_api_proto_v1_invoice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidInvoiceResponse) ProtoMessage() {}

func (x *VoidInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_invoice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidInvoiceResponse.ProtoReflect.Descriptor instead.
func (*VoidInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_invoice_proto_rawDescGZIP(), []int{9}
}

func (x *VoidInvoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VoidInvoiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VoidInvoiceResponse) GetInvoice() *InvoiceResponse {
	if x != nil {
		return x.Invoice
	}
	return nil
}

var File_api_proto_v1_invoice_proto protoreflect.FileDescriptor

const file_api_proto_v1_invoice_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/v1/invoice.proto\x12\x10subscriptions.v1\"\x98\x01\n" +
	"\x13InvoiceItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x01R\x05total\"\xe0\x04\n" +
	"\x0fInvoiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0einvoice_number\x18\x02 \x01(\tR\rinvoiceNumber\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x10\n" +
	"\x03tax\x18\x06 \x01(\x01R\x03tax\x12!\n" +
	"\ftotal_amount\x18\a \x01(\x01R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x19\n" +
	"\bdue_date\x18\n" +
	" \x01(\tR\adueDate\x12\x17\n" +
	"\apaid_at\x18\v \x01(\tR\x06paidAt\x12%\n" +
	"\x0epayment_method\x18\f \x01(\tR\rpaymentMethod\x12+\n" +
	"\x11payment_reference\x18\r \x01(\tR\x10paymentReference\x12:\n" +
	"\x19bank_account_instructions\x18\x0e \x01(\tR\x17bankAccountInstructions\x12\x14\n" +
	"\x05notes\x18\x0f \x01(\tR\x05notes\x12;\n" +
	"\x05items\x18\x10 \x03(\v2%.subscriptions.v1.InvoiceItemResponseR\x05items\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\tR\tupdatedAt\"u\n" +
	"\x16CreateInvoiceItemInput\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\x01R\tunitPrice\"\xd1\x02\n" +
	"\x1aCreateManualInvoiceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x10\n" +
	"\x03tax\x18\x04 \x01(\x01R\x03tax\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x19\n" +
	"\bdue_date\x18\x06 \x01(\tR\adueDate\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12:\n" +
	"\x19bank_account_instructions\x18\b \x01(\tR\x17bankAccountInstructions\x12>\n" +
	"\x05items\x18\t \x03(\v2(.subscriptions.v1.CreateInvoiceItemInputR\x05items\"#\n" +
	"\x11GetInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8f\x01\n" +
	"\x13ListInvoicesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\"\xba\x01\n" +
	"\x14ListInvoicesResponse\x12=\n" +
	"\binvoices\x18\x01 \x03(\v2!.subscriptions.v1.InvoiceResponseR\binvoices\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x03R\n" +
	"totalItems\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xc7\x01\n" +
	"\x16MarkInvoicePaidRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12+\n" +
	"\x11payment_reference\x18\x02 \x01(\tR\x10paymentReference\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vadmin_notes\x18\x04 \x01(\tR\n" +
	"adminNotes\x12\x19\n" +
	"\badmin_id\x18\x05 \x01(\tR\aadminId\"K\n" +
	"\x12VoidInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x86\x01\n" +
	"\x13VoidInvoiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\ainvoice\x18\x03 \x01(\v2!.subscriptions.v1.InvoiceResponseR\ainvoice2\xe9\x03\n" +
	"\x0eInvoiceService\x12f\n" +
	"\x13CreateManualInvoice\x12,.subscriptions.v1.CreateManualInvoiceRequest\x1a!.subscriptions.v1.InvoiceResponse\x12T\n" +
	"\n" +
	"GetInvoice\x12#.subscriptions.v1.GetInvoiceRequest\x1a!.subscriptions.v1.InvoiceResponse\x12]\n" +
	"\fListInvoices\x12%.subscriptions.v1.ListInvoicesRequest\x1a&.subscriptions.v1.ListInvoicesResponse\x12^\n" +
	"\x0fMarkInvoicePaid\x12(.subscriptions.v1.MarkInvoicePaidRequest\x1a!.subscriptions.v1.InvoiceResponse\x12Z\n" +
	"\vVoidInvoice\x12$.subscriptions.v1.VoidInvoiceRequest\x1a%.subscriptions.v1.VoidInvoiceResponseB,Z*subscriptions/api/proto/v1;subscriptionsv1b\x06proto3"

var (
	file_api_proto_v1_invoice_proto_rawDescOnce sync.Once
	file_api_proto_v1_invoice_proto_rawDescData []byte
)

func file_api_proto_v1_invoice_proto_rawDescGZIP() []byte {
	file_api_proto_v1_invoice_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_invoice_proto_rawDesc), len(file_api_proto_v1_invoice_proto_rawDesc)))
	})
	return file_api_proto_v1_invoice_proto_rawDescData
}

var file_api_proto_v1_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_v1_invoice_proto_goTypes = []any{
	(*InvoiceItemResponse)(nil),        // 0: subscriptions.v1.InvoiceItemResponse
	(*InvoiceResponse)(nil),            // 1: subscriptions.v1.InvoiceResponse
	(*CreateInvoiceItemInput)(nil),     // 2: subscriptions.v1.CreateInvoiceItemInput
	(*CreateManualInvoiceRequest)(nil), // 3: subscriptions.v1.CreateManualInvoiceRequest
	(*GetInvoiceRequest)(nil),          // 4: subscriptions.v1.GetInvoiceRequest
	(*ListInvoicesRequest)(nil),        // 5: subscriptions.v1.ListInvoicesRequest
	(*ListInvoicesResponse)(nil),       // 6: subscriptions.v1.ListInvoicesResponse
	(*MarkInvoicePaidRequest)(nil),     // 7: subscriptions.v1.MarkInvoicePaidRequest
	(*VoidInvoiceRequest)(nil),         // 8: subscriptions.v1.VoidInvoiceRequest
	(*VoidInvoiceResponse)(nil),        // 9: subscriptions.v1.VoidInvoiceResponse
}
var file_api_proto_v1_invoice_proto_depIdxs = []int32{
	0, // 0: subscriptions.v1.InvoiceResponse.items:type_name -> subscriptions.v1.InvoiceItemResponse
	2, // 1: subscriptions.v1.CreateManualInvoiceRequest.items:type_name -> subscriptions.v1.CreateInvoiceItemInput
	1, // 2: subscriptions.v1.ListInvoicesResponse.invoices:type_name -> subscriptions.v1.InvoiceResponse
	1, // 3: subscriptions.v1.VoidInvoiceResponse.invoice:type_name -> subscriptions.v1.InvoiceResponse
	3, // 4: subscriptions.v1.InvoiceService.CreateManualInvoice:input_type -> subscriptions.v1.CreateManualInvoiceRequest
	4, // 5: subscriptions.v1.InvoiceService.GetInvoice:input_type -> subscriptions.v1.GetInvoiceRequest
	5, // 6: subscriptions.v1.InvoiceService.ListInvoices:input_type -> subscriptions.v1.ListInvoicesRequest
	7, // 7: subscriptions.v1.InvoiceService.MarkInvoicePaid:input_type -> subscriptions.v1.MarkInvoicePaidRequest
	8, // 8: subscriptions.v1.InvoiceService.VoidInvoice:input_type -> subscriptions.v1.VoidInvoiceRequest
	1, // 9: subscriptions.v1.InvoiceService.CreateManualInvoice:output_type -> subscriptions.v1.InvoiceResponse
	1, // 10: subscriptions.v1.InvoiceService.GetInvoice:output_type -> subscriptions.v1.InvoiceResponse
	6, // 11: subscriptions.v1.InvoiceService.ListInvoices:output_type -> subscriptions.v1.ListInvoicesResponse
	1, // 12: subscriptions.v1.InvoiceService.MarkInvoicePaid:output_type -> subscriptions.v1.InvoiceResponse
	9, // 13: subscriptions.v1.InvoiceService.VoidInvoice:output_type -> subscriptions.v1.VoidInvoiceResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_v1_invoice_proto_init() }
func file_api_proto_v1_invoice_proto_init() {
	if File_api_proto_v1_invoice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_invoice_proto_rawDesc), len(file_api_proto_v1_invoice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_invoice_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_invoice_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_invoice_proto_msgTypes,
	}.Build()
	File_api_proto_v1_invoice_proto = out.File
	file_api_proto_v1_invoice_proto_goTypes = nil
	file_api_proto_v1_invoice_proto_depIdxs = nil
}
