// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/v1/manual_payment.proto

package subscriptionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManualPaymentResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceId            string                 `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	UserId               string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod        string                 `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // bank_transfer, cash, wire, check
	TransactionReference string                 `protobuf:"bytes,7,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	PayerName            string                 `protobuf:"bytes,8,opt,name=payer_name,json=payerName,proto3" json:"payer_name,omitempty"`
	PayerNotes           string                 `protobuf:"bytes,9,opt,name=payer_notes,json=payerNotes,proto3" json:"payer_notes,omitempty"`
	RecordedByAdminId    string                 `protobuf:"bytes,10,opt,name=recorded_by_admin_id,json=recordedByAdminId,proto3" json:"recorded_by_admin_id,omitempty"`
	AdminNotes           string                 `protobuf:"bytes,11,opt,name=admin_notes,json=adminNotes,proto3" json:"admin_notes,omitempty"`
	Status               string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"` // submitted, approved, rejected
	CreatedAt            string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ManualPaymentResponse) Reset() {
	*x = ManualPaymentResponse{}
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualPaymentResponse) ProtoMessage() {}

func (x *ManualPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualPaymentResponse.ProtoReflect.Descriptor instead.
func (*ManualPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_manual_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ManualPaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManualPaymentResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *ManualPaymentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ManualPaymentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ManualPaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ManualPaymentResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *ManualPaymentResponse) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

func (x *ManualPaymentResponse) GetPayerName() string {
	if x != nil {
		return x.PayerName
	}
	return ""
}

func (x *ManualPaymentResponse) GetPayerNotes() string {
	if x != nil {
		return x.PayerNotes
	}
	return ""
}

func (x *ManualPaymentResponse) GetRecordedByAdminId() string {
	if x != nil {
		return x.RecordedByAdminId
	}
	return ""
}

func (x *ManualPaymentResponse) GetAdminNotes() string {
	if x != nil {
		return x.AdminNotes
	}
	return ""
}

func (x *ManualPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ManualPaymentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ManualPaymentResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SubmitManualPaymentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId            string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod        string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TransactionReference string                 `protobuf:"bytes,6,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	PayerName            string                 `protobuf:"bytes,7,opt,name=payer_name,json=payerName,proto3" json:"payer_name,omitempty"`
	PayerNotes           string                 `protobuf:"bytes,8,opt,name=payer_notes,json=payerNotes,proto3" json:"payer_notes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubmitManualPaymentRequest) Reset() {
	*x = SubmitManualPaymentRequest{}
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitManualPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitManualPaymentRequest) ProtoMessage() {}

func (x *SubmitManualPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitManualPaymentRequest.ProtoReflect.Descriptor instead.
func (*SubmitManualPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_manual_payment_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitManualPaymentRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SubmitManualPaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetPayerName() string {
	if x != nil {
		return x.PayerName
	}
	return ""
}

func (x *SubmitManualPaymentRequest) GetPayerNotes() string {
	if x != nil {
		return x.PayerNotes
	}
	return ""
}

type ReviewManualPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Approve       bool                   `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"`
	AdminNotes    string                 `protobuf:"bytes,3,opt,name=admin_notes,json=adminNotes,proto3" json:"admin_notes,omitempty"`
	AdminId       string                 `protobuf:"bytes,4,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewManualPaymentRequest) Reset() {
	*x = ReviewManualPaymentRequest{}
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewManualPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewManualPaymentRequest) ProtoMessage() {}

func (x *ReviewManualPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewManualPaymentRequest.ProtoReflect.Descriptor instead.
func (*ReviewManualPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_manual_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewManualPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ReviewManualPaymentRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *ReviewManualPaymentRequest) GetAdminNotes() string {
	if x != nil {
		return x.AdminNotes
	}
	return ""
}

func (x *ReviewManualPaymentRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type ReviewManualPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payment       *ManualPaymentResponse `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewManualPaymentResponse) Reset() {
	*x = ReviewManualPaymentResponse{}
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewManualPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewManualPaymentResponse) ProtoMessage() {}

func (x *ReviewManualPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewManualPaymentResponse.ProtoReflect.Descriptor instead.
func (*ReviewManualPaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_manual_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewManualPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReviewManualPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReviewManualPaymentResponse) GetPayment() *ManualPaymentResponse {
	if x != nil {
		return x.Payment
	}
	return nil
}

type ListManualPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManualPaymentsRequest) Reset() {
	*x = ListManualPaymentsRequest{}
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManualPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManualPaymentsRequest) ProtoMessage() {}

func (x *ListManualPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManualPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListManualPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_manual_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ListManualPaymentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListManualPaymentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListManualPaymentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListManualPaymentsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListManualPaymentsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Payments      []*ManualPaymentResponse `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	TotalItems    int64                    `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	CurrentPage   int32                    `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                    `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManualPaymentsResponse) Reset() {
	*x = ListManualPaymentsResponse{}
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManualPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManualPaymentsResponse) ProtoMessage() {}

func (x *ListManualPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_manual_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManualPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListManualPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_manual_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListManualPaymentsResponse) GetPayments() []*ManualPaymentResponse {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListManualPaymentsResponse) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ListManualPaymentsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *ListManualPaymentsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_api_proto_v1_manual_payment_proto protoreflect.FileDescriptor

const file_api_proto_v1_manual_payment_proto_rawDesc = "" +
	"\n" +
	"!api/proto/v1/manual_payment.proto\x12\x10subscriptions.v1\"\xd7\x03\n" +
	"\x15ManualPaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x02 \x01(\tR\tinvoiceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x06 \x01(\tR\rpaymentMethod\x123\n" +
	"\x15transaction_reference\x18\a \x01(\tR\x14transactionReference\x12\x1d\n" +
	"\n" +
	"payer_name\x18\b \x01(\tR\tpayerName\x12\x1f\n" +
	"\vpayer_notes\x18\t \x01(\tR\n" +
	"payerNotes\x12/\n" +
	"\x14recorded_by_admin_id\x18\n" +
	" \x01(\tR\x11recordedByAdminId\x12\x1f\n" +
	"\vadmin_notes\x18\v \x01(\tR\n" +
	"adminNotes\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\xa4\x02\n" +
	"\x1aSubmitManualPaymentRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x123\n" +
	"\x15transaction_reference\x18\x06 \x01(\tR\x14transactionReference\x12\x1d\n" +
	"\n" +
	"payer_name\x18\a \x01(\tR\tpayerName\x12\x1f\n" +
	"\vpayer_notes\x18\b \x01(\tR\n" +
	"payerNotes\"\x91\x01\n" +
	"\x1aReviewManualPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x18\n" +
	"\aapprove\x18\x02 \x01(\bR\aapprove\x12\x1f\n" +
	"\vadmin_notes\x18\x03 \x01(\tR\n" +
	"adminNotes\x12\x19\n" +
	"\badmin_id\x18\x04 \x01(\tR\aadminId\"\x94\x01\n" +
	"\x1bReviewManualPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\apayment\x18\x03 \x01(\v2'.subscriptions.v1.ManualPaymentResponseR\apayment\"|\n" +
	"\x19ListManualPaymentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\xc6\x01\n" +
	"\x1aListManualPaymentsResponse\x12C\n" +
	"\bpayments\x18\x01 \x03(\v2'.subscriptions.v1.ManualPaymentResponseR\bpayments\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x03R\n" +
	"totalItems\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages2\xe9\x02\n" +
	"\x14ManualPaymentService\x12l\n" +
	"\x13SubmitManualPayment\x12,.subscriptions.v1.SubmitManualPaymentRequest\x1a'.subscriptions.v1.ManualPaymentResponse\x12r\n" +
	"\x13ReviewManualPayment\x12,.subscriptions.v1.ReviewManualPaymentRequest\x1a-.subscriptions.v1.ReviewManualPaymentResponse\x12o\n" +
	"\x12ListManualPayments\x12+.subscriptions.v1.ListManualPaymentsRequest\x1a,.subscriptions.v1.ListManualPaymentsResponseB,Z*subscriptions/api/proto/v1;subscriptionsv1b\x06proto3"

var (
	file_api_proto_v1_manual_payment_proto_rawDescOnce sync.Once
	file_api_proto_v1_manual_payment_proto_rawDescData []byte
)

func file_api_proto_v1_manual_payment_proto_rawDescGZIP() []byte {
	file_api_proto_v1_manual_payment_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_manual_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_manual_payment_proto_rawDesc), len(file_api_proto_v1_manual_payment_proto_rawDesc)))
	})
	return file_api_proto_v1_manual_payment_proto_rawDescData
}

var file_api_proto_v1_manual_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_v1_manual_payment_proto_goTypes = []any{
	(*ManualPaymentResponse)(nil),       // 0: subscriptions.v1.ManualPaymentResponse
	(*SubmitManualPaymentRequest)(nil),  // 1: subscriptions.v1.SubmitManualPaymentRequest
	(*ReviewManualPaymentRequest)(nil),  // 2: subscriptions.v1.ReviewManualPaymentRequest
	(*ReviewManualPaymentResponse)(nil), // 3: subscriptions.v1.ReviewManualPaymentResponse
	(*ListManualPaymentsRequest)(nil),   // 4: subscriptions.v1.ListManualPaymentsRequest
	(*ListManualPaymentsResponse)(nil),  // 5: subscriptions.v1.ListManualPaymentsResponse
}
var file_api_proto_v1_manual_payment_proto_depIdxs = []int32{
	0, // 0: subscriptions.v1.ReviewManualPaymentResponse.payment:type_name -> subscriptions.v1.ManualPaymentResponse
	0, // 1: subscriptions.v1.ListManualPaymentsResponse.payments:type_name -> subscriptions.v1.ManualPaymentResponse
	1, // 2: subscriptions.v1.ManualPaymentService.SubmitManualPayment:input_type -> subscriptions.v1.SubmitManualPaymentRequest
	2, // 3: subscriptions.v1.ManualPaymentService.ReviewManualPayment:input_type -> subscriptions.v1.ReviewManualPaymentRequest
	4, // 4: subscriptions.v1.ManualPaymentService.ListManualPayments:input_type -> subscriptions.v1.ListManualPaymentsRequest
	0, // 5: subscriptions.v1.ManualPaymentService.SubmitManualPayment:output_type -> subscriptions.v1.ManualPaymentResponse
	3, // 6: subscriptions.v1.ManualPaymentService.ReviewManualPayment:output_type -> subscriptions.v1.ReviewManualPaymentResponse
	5, // 7: subscriptions.v1.ManualPaymentService.ListManualPayments:output_type -> subscriptions.v1.ListManualPaymentsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_manual_payment_proto_init() }
func file_api_proto_v1_manual_payment_proto_init() {
	if File_api_proto_v1_manual_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_manual_payment_proto_rawDesc), len(file_api_proto_v1_manual_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_manual_payment_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_manual_payment_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_manual_payment_proto_msgTypes,
	}.Build()
	File_api_proto_v1_manual_payment_proto = out.File
	file_api_proto_v1_manual_payment_proto_goTypes = nil
	file_api_proto_v1_manual_payment_proto_depIdxs = nil
}
