// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/v1/manual_payment.proto

package subscriptionsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManualPaymentService_SubmitManualPayment_FullMethodName = "/subscriptions.v1.ManualPaymentService/SubmitManualPayment"
	ManualPaymentService_ReviewManualPayment_FullMethodName = "/subscriptions.v1.ManualPaymentService/ReviewManualPayment"
	ManualPaymentService_ListManualPayments_FullMethodName  = "/subscriptions.v1.ManualPaymentService/ListManualPayments"
)

// ManualPaymentServiceClient is the client API for ManualPaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManualPaymentServiceClient interface {
	SubmitManualPayment(ctx context.Context, in *SubmitManualPaymentRequest, opts ...grpc.CallOption) (*ManualPaymentResponse, error)
	ReviewManualPayment(ctx context.Context, in *ReviewManualPaymentRequest, opts ...grpc.CallOption) (*ReviewManualPaymentResponse, error)
	ListManualPayments(ctx context.Context, in *ListManualPaymentsRequest, opts ...grpc.CallOption) (*ListManualPaymentsResponse, error)
}

type manualPaymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManualPaymentServiceClient(cc grpc.ClientConnInterface) ManualPaymentServiceClient {
	return &manualPaymentServiceClient{cc}
}

func (c *manualPaymentServiceClient) SubmitManualPayment(ctx context.Context, in *SubmitManualPaymentRequest, opts ...grpc.CallOption) (*ManualPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManualPaymentResponse)
	err := c.cc.Invoke(ctx, ManualPaymentService_SubmitManualPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manualPaymentServiceClient) ReviewManualPayment(ctx context.Context, in *ReviewManualPaymentRequest, opts ...grpc.CallOption) (*ReviewManualPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewManualPaymentResponse)
	err := c.cc.Invoke(ctx, ManualPaymentService_ReviewManualPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manualPaymentServiceClient) ListManualPayments(ctx context.Context, in *ListManualPaymentsRequest, opts ...grpc.CallOption) (*ListManualPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManualPaymentsResponse)
	err := c.cc.Invoke(ctx, ManualPaymentService_ListManualPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManualPaymentServiceServer is the server API for ManualPaymentService service.
// All implementations must embed UnimplementedManualPaymentServiceServer
// for forward compatibility.
type ManualPaymentServiceServer interface {
	SubmitManualPayment(context.Context, *SubmitManualPaymentRequest) (*ManualPaymentResponse, error)
	ReviewManualPayment(context.Context, *ReviewManualPaymentRequest) (*ReviewManualPaymentResponse, error)
	ListManualPayments(context.Context, *ListManualPaymentsRequest) (*ListManualPaymentsResponse, error)
	mustEmbedUnimplementedManualPaymentServiceServer()
}

// UnimplementedManualPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManualPaymentServiceServer struct{}

func (UnimplementedManualPaymentServiceServer) SubmitManualPayment(context.Context, *SubmitManualPaymentRequest) (*ManualPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitManualPayment not implemented")
}
func (UnimplementedManualPaymentServiceServer) ReviewManualPayment(context.Context, *ReviewManualPaymentRequest) (*ReviewManualPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewManualPayment not implemented")
}
func (UnimplementedManualPaymentServiceServer) ListManualPayments(context.Context, *ListManualPaymentsRequest) (*ListManualPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManualPayments not implemented")
}
func (UnimplementedManualPaymentServiceServer) mustEmbedUnimplementedManualPaymentServiceServer() {}
func (UnimplementedManualPaymentServiceServer) testEmbeddedByValue()                              {}

// UnsafeManualPaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManualPaymentServiceServer will
// result in compilation errors.
type UnsafeManualPaymentServiceServer interface {
	mustEmbedUnimplementedManualPaymentServiceServer()
}

func RegisterManualPaymentServiceServer(s grpc.ServiceRegistrar, srv ManualPaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedManualPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManualPaymentService_ServiceDesc, srv)
}

func _ManualPaymentService_SubmitManualPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitManualPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManualPaymentServiceServer).SubmitManualPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManualPaymentService_SubmitManualPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManualPaymentServiceServer).SubmitManualPayment(ctx, req.(*SubmitManualPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManualPaymentService_ReviewManualPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewManualPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManualPaymentServiceServer).ReviewManualPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManualPaymentService_ReviewManualPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManualPaymentServiceServer).ReviewManualPayment(ctx, req.(*ReviewManualPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManualPaymentService_ListManualPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManualPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManualPaymentServiceServer).ListManualPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManualPaymentService_ListManualPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManualPaymentServiceServer).ListManualPayments(ctx, req.(*ListManualPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManualPaymentService_ServiceDesc is the grpc.ServiceDesc for ManualPaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManualPaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscriptions.v1.ManualPaymentService",
	HandlerType: (*ManualPaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitManualPayment",
			Handler:    _ManualPaymentService_SubmitManualPayment_Handler,
		},
		{
			MethodName: "ReviewManualPayment",
			Handler:    _ManualPaymentService_ReviewManualPayment_Handler,
		},
		{
			MethodName: "ListManualPayments",
			Handler:    _ManualPaymentService_ListManualPayments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/manual_payment.proto",
}
