// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: country.proto

package accountsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCountriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesRequest) Reset() {
	*x = ListCountriesRequest{}
	mi := &file_country_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesRequest) ProtoMessage() {}

func (x *ListCountriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesRequest.ProtoReflect.Descriptor instead.
func (*ListCountriesRequest) Descriptor() ([]byte, []int) {
	return file_country_proto_rawDescGZIP(), []int{0}
}

func (x *ListCountriesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListCountriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*CountryResponse     `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCountriesResponse) Reset() {
	*x = ListCountriesResponse{}
	mi := &file_country_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCountriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCountriesResponse) ProtoMessage() {}

func (x *ListCountriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_country_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCountriesResponse.ProtoReflect.Descriptor instead.
func (*ListCountriesResponse) Descriptor() ([]byte, []int) {
	return file_country_proto_rawDescGZIP(), []int{1}
}

func (x *ListCountriesResponse) GetCountries() []*CountryResponse {
	if x != nil {
		return x.Countries
	}
	return nil
}

type GetCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CountryCode   string                 `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountryRequest) Reset() {
	*x = GetCountryRequest{}
	mi := &file_country_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountryRequest) ProtoMessage() {}

func (x *GetCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountryRequest.ProtoReflect.Descriptor instead.
func (*GetCountryRequest) Descriptor() ([]byte, []int) {
	return file_country_proto_rawDescGZIP(), []int{2}
}

func (x *GetCountryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCountryRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

var File_country_proto protoreflect.FileDescriptor

const file_country_proto_rawDesc = "" +
	"\n" +
	"\rcountry.proto\x12\vaccounts.v1\x1a\fcommon.proto\".\n" +
	"\x14ListCountriesRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\"S\n" +
	"\x15ListCountriesResponse\x12:\n" +
	"\tcountries\x18\x01 \x03(\v2\x1c.accounts.v1.CountryResponseR\tcountries\"F\n" +
	"\x11GetCountryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode2\xb4\x01\n" +
	"\x0eCountryService\x12V\n" +
	"\rListCountries\x12!.accounts.v1.ListCountriesRequest\x1a\".accounts.v1.ListCountriesResponse\x12J\n" +
	"\n" +
	"GetCountry\x12\x1e.accounts.v1.GetCountryRequest\x1a\x1c.accounts.v1.CountryResponseB\"Z accounts/api/proto/v1;accountsv1b\x06proto3"

var (
	file_country_proto_rawDescOnce sync.Once
	file_country_proto_rawDescData []byte
)

func file_country_proto_rawDescGZIP() []byte {
	file_country_proto_rawDescOnce.Do(func() {
		file_country_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_country_proto_rawDesc), len(file_country_proto_rawDesc)))
	})
	return file_country_proto_rawDescData
}

var file_country_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_country_proto_goTypes = []any{
	(*ListCountriesRequest)(nil),  // 0: accounts.v1.ListCountriesRequest
	(*ListCountriesResponse)(nil), // 1: accounts.v1.ListCountriesResponse
	(*GetCountryRequest)(nil),     // 2: accounts.v1.GetCountryRequest
	(*CountryResponse)(nil),       // 3: accounts.v1.CountryResponse
}
var file_country_proto_depIdxs = []int32{
	3, // 0: accounts.v1.ListCountriesResponse.countries:type_name -> accounts.v1.CountryResponse
	0, // 1: accounts.v1.CountryService.ListCountries:input_type -> accounts.v1.ListCountriesRequest
	2, // 2: accounts.v1.CountryService.GetCountry:input_type -> accounts.v1.GetCountryRequest
	1, // 3: accounts.v1.CountryService.ListCountries:output_type -> accounts.v1.ListCountriesResponse
	3, // 4: accounts.v1.CountryService.GetCountry:output_type -> accounts.v1.CountryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_country_proto_init() }
func file_country_proto_init() {
	if File_country_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_country_proto_rawDesc), len(file_country_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_country_proto_goTypes,
		DependencyIndexes: file_country_proto_depIdxs,
		MessageInfos:      file_country_proto_msgTypes,
	}.Build()
	File_country_proto = out.File
	file_country_proto_goTypes = nil
	file_country_proto_depIdxs = nil
}
