// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/proto/v1/request_tracker.proto

package requesttrackerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ActorType     string                 `protobuf:"bytes,4,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // ADMIN, USER, ANONYMOUS, SYSTEM
	ActorId       string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorName     string                 `protobuf:"bytes,6,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	ActorEmail    string                 `protobuf:"bytes,7,opt,name=actor_email,json=actorEmail,proto3" json:"actor_email,omitempty"`
	ActorRole     string                 `protobuf:"bytes,8,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"`
	ServiceName   string                 `protobuf:"bytes,9,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Method        string                 `protobuf:"bytes,10,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,11,opt,name=path,proto3" json:"path,omitempty"`
	Route         string                 `protobuf:"bytes,12,opt,name=route,proto3" json:"route,omitempty"`
	QueryParams   string                 `protobuf:"bytes,13,opt,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	ClientIp      string                 `protobuf:"bytes,14,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,15,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	StatusCode    int32                  `protobuf:"varint,16,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LifetimeMs    float64                `protobuf:"fixed64,17,opt,name=lifetime_ms,json=lifetimeMs,proto3" json:"lifetime_ms,omitempty"`
	RequestBody   string                 `protobuf:"bytes,18,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseBody  string                 `protobuf:"bytes,19,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,20,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SpansJson     string                 `protobuf:"bytes,21,opt,name=spans_json,json=spansJson,proto3" json:"spans_json,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,22,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,23,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTrace) Reset() {
	*x = RequestTrace{}
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTrace) ProtoMessage() {}

func (x *RequestTrace) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTrace.ProtoReflect.Descriptor instead.
func (*RequestTrace) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_request_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *RequestTrace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestTrace) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RequestTrace) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestTrace) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *RequestTrace) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RequestTrace) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *RequestTrace) GetActorEmail() string {
	if x != nil {
		return x.ActorEmail
	}
	return ""
}

func (x *RequestTrace) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

func (x *RequestTrace) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RequestTrace) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestTrace) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestTrace) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *RequestTrace) GetQueryParams() string {
	if x != nil {
		return x.QueryParams
	}
	return ""
}

func (x *RequestTrace) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *RequestTrace) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RequestTrace) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RequestTrace) GetLifetimeMs() float64 {
	if x != nil {
		return x.LifetimeMs
	}
	return 0
}

func (x *RequestTrace) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *RequestTrace) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *RequestTrace) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RequestTrace) GetSpansJson() string {
	if x != nil {
		return x.SpansJson
	}
	return ""
}

func (x *RequestTrace) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *RequestTrace) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type RecordTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trace         *RequestTrace          `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTraceRequest) Reset() {
	*x = RecordTraceRequest{}
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTraceRequest) ProtoMessage() {}

func (x *RecordTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTraceRequest.ProtoReflect.Descriptor instead.
func (*RecordTraceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_request_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *RecordTraceRequest) GetTrace() *RequestTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type RecordTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Trace         *RequestTrace          `protobuf:"bytes,3,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTraceResponse) Reset() {
	*x = RecordTraceResponse{}
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTraceResponse) ProtoMessage() {}

func (x *RecordTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTraceResponse.ProtoReflect.Descriptor instead.
func (*RecordTraceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_request_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *RecordTraceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordTraceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecordTraceResponse) GetTrace() *RequestTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type ListTracesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorType     string                 `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Route         string                 `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	MinLifetimeMs float64                `protobuf:"fixed64,6,opt,name=min_lifetime_ms,json=minLifetimeMs,proto3" json:"min_lifetime_ms,omitempty"`
	Search        string                 `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
	StartDate     string                 `protobuf:"bytes,8,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,9,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page          int32                  `protobuf:"varint,10,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,11,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracesRequest) Reset() {
	*x = ListTracesRequest{}
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracesRequest) ProtoMessage() {}

func (x *ListTracesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracesRequest.ProtoReflect.Descriptor instead.
func (*ListTracesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_request_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *ListTracesRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *ListTracesRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ListTracesRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ListTracesRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *ListTracesRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListTracesRequest) GetMinLifetimeMs() float64 {
	if x != nil {
		return x.MinLifetimeMs
	}
	return 0
}

func (x *ListTracesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListTracesRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListTracesRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ListTracesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTracesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTracesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*RequestTrace        `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracesResponse) Reset() {
	*x = ListTracesResponse{}
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracesResponse) ProtoMessage() {}

func (x *ListTracesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracesResponse.ProtoReflect.Descriptor instead.
func (*ListTracesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_request_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *ListTracesResponse) GetTraces() []*RequestTrace {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *ListTracesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTracesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTracesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Can be trace_id or primary UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceRequest) Reset() {
	*x = GetTraceRequest{}
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceRequest) ProtoMessage() {}

func (x *GetTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceRequest.ProtoReflect.Descriptor instead.
func (*GetTraceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_request_tracker_proto_rawDescGZIP(), []int{5}
}

func (x *GetTraceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trace         *RequestTrace          `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceResponse) Reset() {
	*x = GetTraceResponse{}
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceResponse) ProtoMessage() {}

func (x *GetTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceResponse.ProtoReflect.Descriptor instead.
func (*GetTraceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_request_tracker_proto_rawDescGZIP(), []int{6}
}

func (x *GetTraceResponse) GetTrace() *RequestTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type GetTraceStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceStatsRequest) Reset() {
	*x = GetTraceStatsRequest{}
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceStatsRequest) ProtoMessage() {}

func (x *GetTraceStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceStatsRequest.ProtoReflect.Descriptor instead.
func (*GetTraceStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_request_tracker_proto_rawDescGZIP(), []int{7}
}

func (x *GetTraceStatsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetTraceStatsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetTraceStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	AvgLifetimeMs float64                `protobuf:"fixed64,2,opt,name=avg_lifetime_ms,json=avgLifetimeMs,proto3" json:"avg_lifetime_ms,omitempty"`
	P95LifetimeMs float64                `protobuf:"fixed64,3,opt,name=p95_lifetime_ms,json=p95LifetimeMs,proto3" json:"p95_lifetime_ms,omitempty"`
	P99LifetimeMs float64                `protobuf:"fixed64,4,opt,name=p99_lifetime_ms,json=p99LifetimeMs,proto3" json:"p99_lifetime_ms,omitempty"`
	ErrorCount    int64                  `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	ErrorRate     float64                `protobuf:"fixed64,6,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceStatsResponse) Reset() {
	*x = GetTraceStatsResponse{}
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceStatsResponse) ProtoMessage() {}

func (x *GetTraceStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_request_tracker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceStatsResponse.ProtoReflect.Descriptor instead.
func (*GetTraceStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_request_tracker_proto_rawDescGZIP(), []int{8}
}

func (x *GetTraceStatsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *GetTraceStatsResponse) GetAvgLifetimeMs() float64 {
	if x != nil {
		return x.AvgLifetimeMs
	}
	return 0
}

func (x *GetTraceStatsResponse) GetP95LifetimeMs() float64 {
	if x != nil {
		return x.P95LifetimeMs
	}
	return 0
}

func (x *GetTraceStatsResponse) GetP99LifetimeMs() float64 {
	if x != nil {
		return x.P99LifetimeMs
	}
	return 0
}

func (x *GetTraceStatsResponse) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *GetTraceStatsResponse) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

var File_api_proto_v1_request_tracker_proto protoreflect.FileDescriptor

const file_api_proto_v1_request_tracker_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/v1/request_tracker.proto\x12\x12request_tracker.v1\"\xc7\x05\n" +
	"\fRequestTrace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x04 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x06 \x01(\tR\tactorName\x12\x1f\n" +
	"\vactor_email\x18\a \x01(\tR\n" +
	"actorEmail\x12\x1d\n" +
	"\n" +
	"actor_role\x18\b \x01(\tR\tactorRole\x12!\n" +
	"\fservice_name\x18\t \x01(\tR\vserviceName\x12\x16\n" +
	"\x06method\x18\n" +
	" \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\v \x01(\tR\x04path\x12\x14\n" +
	"\x05route\x18\f \x01(\tR\x05route\x12!\n" +
	"\fquery_params\x18\r \x01(\tR\vqueryParams\x12\x1b\n" +
	"\tclient_ip\x18\x0e \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x0f \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vstatus_code\x18\x10 \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\vlifetime_ms\x18\x11 \x01(\x01R\n" +
	"lifetimeMs\x12!\n" +
	"\frequest_body\x18\x12 \x01(\tR\vrequestBody\x12#\n" +
	"\rresponse_body\x18\x13 \x01(\tR\fresponseBody\x12#\n" +
	"\rerror_message\x18\x14 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"spans_json\x18\x15 \x01(\tR\tspansJson\x12\x1f\n" +
	"\vreceived_at\x18\x16 \x01(\tR\n" +
	"receivedAt\x12!\n" +
	"\fcompleted_at\x18\x17 \x01(\tR\vcompletedAt\"L\n" +
	"\x12RecordTraceRequest\x126\n" +
	"\x05trace\x18\x01 \x01(\v2 .request_tracker.v1.RequestTraceR\x05trace\"\x81\x01\n" +
	"\x13RecordTraceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x05trace\x18\x03 \x01(\v2 .request_tracker.v1.RequestTraceR\x05trace\"\xc0\x02\n" +
	"\x11ListTracesRequest\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x01 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x14\n" +
	"\x05route\x18\x04 \x01(\tR\x05route\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12&\n" +
	"\x0fmin_lifetime_ms\x18\x06 \x01(\x01R\rminLifetimeMs\x12\x16\n" +
	"\x06search\x18\a \x01(\tR\x06search\x12\x1d\n" +
	"\n" +
	"start_date\x18\b \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\t \x01(\tR\aendDate\x12\x12\n" +
	"\x04page\x18\n" +
	" \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\v \x01(\x05R\x05limit\"\x8e\x01\n" +
	"\x12ListTracesResponse\x128\n" +
	"\x06traces\x18\x01 \x03(\v2 .request_tracker.v1.RequestTraceR\x06traces\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"!\n" +
	"\x0fGetTraceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x10GetTraceResponse\x126\n" +
	"\x05trace\x18\x01 \x01(\v2 .request_tracker.v1.RequestTraceR\x05trace\"P\n" +
	"\x14GetTraceStatsRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"\xf6\x01\n" +
	"\x15GetTraceStatsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12&\n" +
	"\x0favg_lifetime_ms\x18\x02 \x01(\x01R\ravgLifetimeMs\x12&\n" +
	"\x0fp95_lifetime_ms\x18\x03 \x01(\x01R\rp95LifetimeMs\x12&\n" +
	"\x0fp99_lifetime_ms\x18\x04 \x01(\x01R\rp99LifetimeMs\x12\x1f\n" +
	"\verror_count\x18\x05 \x01(\x03R\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x06 \x01(\x01R\terrorRate2\x91\x03\n" +
	"\x15RequestTrackerService\x12^\n" +
	"\vRecordTrace\x12&.request_tracker.v1.RecordTraceRequest\x1a'.request_tracker.v1.RecordTraceResponse\x12[\n" +
	"\n" +
	"ListTraces\x12%.request_tracker.v1.ListTracesRequest\x1a&.request_tracker.v1.ListTracesResponse\x12U\n" +
	"\bGetTrace\x12#.request_tracker.v1.GetTraceRequest\x1a$.request_tracker.v1.GetTraceResponse\x12d\n" +
	"\rGetTraceStats\x12(.request_tracker.v1.GetTraceStatsRequest\x1a).request_tracker.v1.GetTraceStatsResponseB5Z3requestTrackerService/api/proto/v1;requesttrackerv1b\x06proto3"

var (
	file_api_proto_v1_request_tracker_proto_rawDescOnce sync.Once
	file_api_proto_v1_request_tracker_proto_rawDescData []byte
)

func file_api_proto_v1_request_tracker_proto_rawDescGZIP() []byte {
	file_api_proto_v1_request_tracker_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_request_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_request_tracker_proto_rawDesc), len(file_api_proto_v1_request_tracker_proto_rawDesc)))
	})
	return file_api_proto_v1_request_tracker_proto_rawDescData
}

var file_api_proto_v1_request_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_v1_request_tracker_proto_goTypes = []any{
	(*RequestTrace)(nil),          // 0: request_tracker.v1.RequestTrace
	(*RecordTraceRequest)(nil),    // 1: request_tracker.v1.RecordTraceRequest
	(*RecordTraceResponse)(nil),   // 2: request_tracker.v1.RecordTraceResponse
	(*ListTracesRequest)(nil),     // 3: request_tracker.v1.ListTracesRequest
	(*ListTracesResponse)(nil),    // 4: request_tracker.v1.ListTracesResponse
	(*GetTraceRequest)(nil),       // 5: request_tracker.v1.GetTraceRequest
	(*GetTraceResponse)(nil),      // 6: request_tracker.v1.GetTraceResponse
	(*GetTraceStatsRequest)(nil),  // 7: request_tracker.v1.GetTraceStatsRequest
	(*GetTraceStatsResponse)(nil), // 8: request_tracker.v1.GetTraceStatsResponse
}
var file_api_proto_v1_request_tracker_proto_depIdxs = []int32{
	0, // 0: request_tracker.v1.RecordTraceRequest.trace:type_name -> request_tracker.v1.RequestTrace
	0, // 1: request_tracker.v1.RecordTraceResponse.trace:type_name -> request_tracker.v1.RequestTrace
	0, // 2: request_tracker.v1.ListTracesResponse.traces:type_name -> request_tracker.v1.RequestTrace
	0, // 3: request_tracker.v1.GetTraceResponse.trace:type_name -> request_tracker.v1.RequestTrace
	1, // 4: request_tracker.v1.RequestTrackerService.RecordTrace:input_type -> request_tracker.v1.RecordTraceRequest
	3, // 5: request_tracker.v1.RequestTrackerService.ListTraces:input_type -> request_tracker.v1.ListTracesRequest
	5, // 6: request_tracker.v1.RequestTrackerService.GetTrace:input_type -> request_tracker.v1.GetTraceRequest
	7, // 7: request_tracker.v1.RequestTrackerService.GetTraceStats:input_type -> request_tracker.v1.GetTraceStatsRequest
	2, // 8: request_tracker.v1.RequestTrackerService.RecordTrace:output_type -> request_tracker.v1.RecordTraceResponse
	4, // 9: request_tracker.v1.RequestTrackerService.ListTraces:output_type -> request_tracker.v1.ListTracesResponse
	6, // 10: request_tracker.v1.RequestTrackerService.GetTrace:output_type -> request_tracker.v1.GetTraceResponse
	8, // 11: request_tracker.v1.RequestTrackerService.GetTraceStats:output_type -> request_tracker.v1.GetTraceStatsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_v1_request_tracker_proto_init() }
func file_api_proto_v1_request_tracker_proto_init() {
	if File_api_proto_v1_request_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_request_tracker_proto_rawDesc), len(file_api_proto_v1_request_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_request_tracker_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_request_tracker_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_request_tracker_proto_msgTypes,
	}.Build()
	File_api_proto_v1_request_tracker_proto = out.File
	file_api_proto_v1_request_tracker_proto_goTypes = nil
	file_api_proto_v1_request_tracker_proto_depIdxs = nil
}
