// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/request_tracker/v1/request_tracker.proto

package requesttrackerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequestTrackerService_RecordTrace_FullMethodName   = "/request_tracker.v1.RequestTrackerService/RecordTrace"
	RequestTrackerService_ListTraces_FullMethodName    = "/request_tracker.v1.RequestTrackerService/ListTraces"
	RequestTrackerService_GetTrace_FullMethodName      = "/request_tracker.v1.RequestTrackerService/GetTrace"
	RequestTrackerService_GetTraceStats_FullMethodName = "/request_tracker.v1.RequestTrackerService/GetTraceStats"
)

// RequestTrackerServiceClient is the client API for RequestTrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RequestTrackerServiceClient interface {
	RecordTrace(ctx context.Context, in *RecordTraceRequest, opts ...grpc.CallOption) (*RecordTraceResponse, error)
	ListTraces(ctx context.Context, in *ListTracesRequest, opts ...grpc.CallOption) (*ListTracesResponse, error)
	GetTrace(ctx context.Context, in *GetTraceRequest, opts ...grpc.CallOption) (*GetTraceResponse, error)
	GetTraceStats(ctx context.Context, in *GetTraceStatsRequest, opts ...grpc.CallOption) (*GetTraceStatsResponse, error)
}

type requestTrackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestTrackerServiceClient(cc grpc.ClientConnInterface) RequestTrackerServiceClient {
	return &requestTrackerServiceClient{cc}
}

func (c *requestTrackerServiceClient) RecordTrace(ctx context.Context, in *RecordTraceRequest, opts ...grpc.CallOption) (*RecordTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordTraceResponse)
	err := c.cc.Invoke(ctx, RequestTrackerService_RecordTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestTrackerServiceClient) ListTraces(ctx context.Context, in *ListTracesRequest, opts ...grpc.CallOption) (*ListTracesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTracesResponse)
	err := c.cc.Invoke(ctx, RequestTrackerService_ListTraces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestTrackerServiceClient) GetTrace(ctx context.Context, in *GetTraceRequest, opts ...grpc.CallOption) (*GetTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTraceResponse)
	err := c.cc.Invoke(ctx, RequestTrackerService_GetTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestTrackerServiceClient) GetTraceStats(ctx context.Context, in *GetTraceStatsRequest, opts ...grpc.CallOption) (*GetTraceStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTraceStatsResponse)
	err := c.cc.Invoke(ctx, RequestTrackerService_GetTraceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestTrackerServiceServer is the server API for RequestTrackerService service.
// All implementations must embed UnimplementedRequestTrackerServiceServer
// for forward compatibility.
type RequestTrackerServiceServer interface {
	RecordTrace(context.Context, *RecordTraceRequest) (*RecordTraceResponse, error)
	ListTraces(context.Context, *ListTracesRequest) (*ListTracesResponse, error)
	GetTrace(context.Context, *GetTraceRequest) (*GetTraceResponse, error)
	GetTraceStats(context.Context, *GetTraceStatsRequest) (*GetTraceStatsResponse, error)
	mustEmbedUnimplementedRequestTrackerServiceServer()
}

// UnimplementedRequestTrackerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestTrackerServiceServer struct{}

func (UnimplementedRequestTrackerServiceServer) RecordTrace(context.Context, *RecordTraceRequest) (*RecordTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordTrace not implemented")
}
func (UnimplementedRequestTrackerServiceServer) ListTraces(context.Context, *ListTracesRequest) (*ListTracesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTraces not implemented")
}
func (UnimplementedRequestTrackerServiceServer) GetTrace(context.Context, *GetTraceRequest) (*GetTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrace not implemented")
}
func (UnimplementedRequestTrackerServiceServer) GetTraceStats(context.Context, *GetTraceStatsRequest) (*GetTraceStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraceStats not implemented")
}
func (UnimplementedRequestTrackerServiceServer) mustEmbedUnimplementedRequestTrackerServiceServer() {}
func (UnimplementedRequestTrackerServiceServer) testEmbeddedByValue()                               {}

// UnsafeRequestTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestTrackerServiceServer will
// result in compilation errors.
type UnsafeRequestTrackerServiceServer interface {
	mustEmbedUnimplementedRequestTrackerServiceServer()
}

func RegisterRequestTrackerServiceServer(s grpc.ServiceRegistrar, srv RequestTrackerServiceServer) {
	// If the following call panics, it indicates UnimplementedRequestTrackerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestTrackerService_ServiceDesc, srv)
}

func _RequestTrackerService_RecordTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestTrackerServiceServer).RecordTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestTrackerService_RecordTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestTrackerServiceServer).RecordTrace(ctx, req.(*RecordTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestTrackerService_ListTraces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTracesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestTrackerServiceServer).ListTraces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestTrackerService_ListTraces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestTrackerServiceServer).ListTraces(ctx, req.(*ListTracesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestTrackerService_GetTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestTrackerServiceServer).GetTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestTrackerService_GetTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestTrackerServiceServer).GetTrace(ctx, req.(*GetTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestTrackerService_GetTraceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestTrackerServiceServer).GetTraceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestTrackerService_GetTraceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestTrackerServiceServer).GetTraceStats(ctx, req.(*GetTraceStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestTrackerService_ServiceDesc is the grpc.ServiceDesc for RequestTrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestTrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "request_tracker.v1.RequestTrackerService",
	HandlerType: (*RequestTrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordTrace",
			Handler:    _RequestTrackerService_RecordTrace_Handler,
		},
		{
			MethodName: "ListTraces",
			Handler:    _RequestTrackerService_ListTraces_Handler,
		},
		{
			MethodName: "GetTrace",
			Handler:    _RequestTrackerService_GetTrace_Handler,
		},
		{
			MethodName: "GetTraceStats",
			Handler:    _RequestTrackerService_GetTraceStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/request_tracker/v1/request_tracker.proto",
}
