// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: webhook.proto

package webhookRunnerV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookRunnerService_SendWebhook_FullMethodName      = "/webhook_runner.v1.WebhookRunnerService/SendWebhook"
	WebhookRunnerService_ListWebhookCalls_FullMethodName = "/webhook_runner.v1.WebhookRunnerService/ListWebhookCalls"
	WebhookRunnerService_GetWebhookCall_FullMethodName   = "/webhook_runner.v1.WebhookRunnerService/GetWebhookCall"
	WebhookRunnerService_RetryWebhookCall_FullMethodName = "/webhook_runner.v1.WebhookRunnerService/RetryWebhookCall"
)

// WebhookRunnerServiceClient is the client API for WebhookRunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhookRunnerServiceClient interface {
	SendWebhook(ctx context.Context, in *SendWebhookRequest, opts ...grpc.CallOption) (*SendWebhookResponse, error)
	ListWebhookCalls(ctx context.Context, in *ListWebhookCallsRequest, opts ...grpc.CallOption) (*ListWebhookCallsResponse, error)
	GetWebhookCall(ctx context.Context, in *GetWebhookCallRequest, opts ...grpc.CallOption) (*GetWebhookCallResponse, error)
	RetryWebhookCall(ctx context.Context, in *RetryWebhookCallRequest, opts ...grpc.CallOption) (*RetryWebhookCallResponse, error)
}

type webhookRunnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookRunnerServiceClient(cc grpc.ClientConnInterface) WebhookRunnerServiceClient {
	return &webhookRunnerServiceClient{cc}
}

func (c *webhookRunnerServiceClient) SendWebhook(ctx context.Context, in *SendWebhookRequest, opts ...grpc.CallOption) (*SendWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookRunnerService_SendWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookRunnerServiceClient) ListWebhookCalls(ctx context.Context, in *ListWebhookCallsRequest, opts ...grpc.CallOption) (*ListWebhookCallsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebhookCallsResponse)
	err := c.cc.Invoke(ctx, WebhookRunnerService_ListWebhookCalls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookRunnerServiceClient) GetWebhookCall(ctx context.Context, in *GetWebhookCallRequest, opts ...grpc.CallOption) (*GetWebhookCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookCallResponse)
	err := c.cc.Invoke(ctx, WebhookRunnerService_GetWebhookCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookRunnerServiceClient) RetryWebhookCall(ctx context.Context, in *RetryWebhookCallRequest, opts ...grpc.CallOption) (*RetryWebhookCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryWebhookCallResponse)
	err := c.cc.Invoke(ctx, WebhookRunnerService_RetryWebhookCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookRunnerServiceServer is the server API for WebhookRunnerService service.
// All implementations must embed UnimplementedWebhookRunnerServiceServer
// for forward compatibility.
type WebhookRunnerServiceServer interface {
	SendWebhook(context.Context, *SendWebhookRequest) (*SendWebhookResponse, error)
	ListWebhookCalls(context.Context, *ListWebhookCallsRequest) (*ListWebhookCallsResponse, error)
	GetWebhookCall(context.Context, *GetWebhookCallRequest) (*GetWebhookCallResponse, error)
	RetryWebhookCall(context.Context, *RetryWebhookCallRequest) (*RetryWebhookCallResponse, error)
	mustEmbedUnimplementedWebhookRunnerServiceServer()
}

// UnimplementedWebhookRunnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookRunnerServiceServer struct{}

func (UnimplementedWebhookRunnerServiceServer) SendWebhook(context.Context, *SendWebhookRequest) (*SendWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendWebhook not implemented")
}
func (UnimplementedWebhookRunnerServiceServer) ListWebhookCalls(context.Context, *ListWebhookCallsRequest) (*ListWebhookCallsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebhookCalls not implemented")
}
func (UnimplementedWebhookRunnerServiceServer) GetWebhookCall(context.Context, *GetWebhookCallRequest) (*GetWebhookCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhookCall not implemented")
}
func (UnimplementedWebhookRunnerServiceServer) RetryWebhookCall(context.Context, *RetryWebhookCallRequest) (*RetryWebhookCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryWebhookCall not implemented")
}
func (UnimplementedWebhookRunnerServiceServer) mustEmbedUnimplementedWebhookRunnerServiceServer() {}
func (UnimplementedWebhookRunnerServiceServer) testEmbeddedByValue()                              {}

// UnsafeWebhookRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookRunnerServiceServer will
// result in compilation errors.
type UnsafeWebhookRunnerServiceServer interface {
	mustEmbedUnimplementedWebhookRunnerServiceServer()
}

func RegisterWebhookRunnerServiceServer(s grpc.ServiceRegistrar, srv WebhookRunnerServiceServer) {
	// If the following call panics, it indicates UnimplementedWebhookRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookRunnerService_ServiceDesc, srv)
}

func _WebhookRunnerService_SendWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookRunnerServiceServer).SendWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookRunnerService_SendWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookRunnerServiceServer).SendWebhook(ctx, req.(*SendWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookRunnerService_ListWebhookCalls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhookCallsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookRunnerServiceServer).ListWebhookCalls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookRunnerService_ListWebhookCalls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookRunnerServiceServer).ListWebhookCalls(ctx, req.(*ListWebhookCallsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookRunnerService_GetWebhookCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookRunnerServiceServer).GetWebhookCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookRunnerService_GetWebhookCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookRunnerServiceServer).GetWebhookCall(ctx, req.(*GetWebhookCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookRunnerService_RetryWebhookCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryWebhookCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookRunnerServiceServer).RetryWebhookCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookRunnerService_RetryWebhookCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookRunnerServiceServer).RetryWebhookCall(ctx, req.(*RetryWebhookCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookRunnerService_ServiceDesc is the grpc.ServiceDesc for WebhookRunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookRunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webhook_runner.v1.WebhookRunnerService",
	HandlerType: (*WebhookRunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWebhook",
			Handler:    _WebhookRunnerService_SendWebhook_Handler,
		},
		{
			MethodName: "ListWebhookCalls",
			Handler:    _WebhookRunnerService_ListWebhookCalls_Handler,
		},
		{
			MethodName: "GetWebhookCall",
			Handler:    _WebhookRunnerService_GetWebhookCall_Handler,
		},
		{
			MethodName: "RetryWebhookCall",
			Handler:    _WebhookRunnerService_RetryWebhookCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webhook.proto",
}
